<!DOCTYPE html><html lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<title>Widgets</title>
<!--Generated by LaTeXML oxide (version 0.7.6) http://dlmf.nist.gov/LaTeXML/.-->
<link rel="stylesheet" href="LaTeXML.css" type="text/css">
<link rel="stylesheet" href="ltx-article.css" type="text/css"><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>
<body>
<div class="ltx_page_main">
<div class="ltx_page_content">
<article class="ltx_document">
<h1 class="ltx_title ltx_title_document">Interactive Fixture</h1>
<div class="ltx_authors">
<span class="ltx_creator ltx_role_author">
<span class="ltx_personname">Ada Lovelace</span></span></div>
<div id="abstract1" class="ltx_abstract"><h6 class="ltx_title ltx_title_abstract">Abstract</h6>
<p class="ltx_p">Five widgets and two plain figures.</p>
</div>
<section id="S1" class="ltx_section">
<h2 class="ltx_title ltx_title_section"><span class="ltx_tag ltx_tag_section">1 </span>Widgets</h2>
<figure id="S1.F1" class="ltx_figure">
<figcaption class="ltx_caption ltx_centering"><span class="ltx_tag ltx_tag_figure">Figure 1: </span>A model.</figcaption><span class="ltx_text ltx_centering m-widget m-widget-model"></span>
</figure>
<figure id="S1.F2" class="ltx_figure"><span class="ltx_text ltx_centering m-widget m-widget-video"></span>
<figcaption class="ltx_caption ltx_centering"><span class="ltx_tag ltx_tag_figure">Figure 2: </span>A video.</figcaption>
</figure>
<div id="S1.p1" class="ltx_para">
<p class="ltx_p"><span class="ltx_text m-widget m-widget-table"></span>
<span class="ltx_text m-widget m-widget-chart"></span>
<span class="ltx_text m-widget m-widget-html"></span></p>
</div>
<section id="S1.SS1" class="ltx_subsection">
<h3 class="ltx_title ltx_title_subsection"><span class="ltx_tag ltx_tag_subsection">1.1 </span>Plain figures</h3>
<figure id="S1.F3" class="ltx_figure"><img src="" id="S1.F3.g1" class="ltx_graphics ltx_centering ltx_missing ltx_missing_image" alt="Refer to caption" data-graphic="figures/mesh">
<figcaption class="ltx_caption ltx_centering"><span class="ltx_tag ltx_tag_figure">Figure 3: </span>The mesh as a plain figure.</figcaption>
</figure>
<figure id="S1.F4" class="ltx_figure"><img src="" id="S1.F4.g1" class="ltx_graphics ltx_centering ltx_missing ltx_missing_image" alt="Refer to caption" data-graphic="figures/absent.png">
<figcaption class="ltx_caption ltx_centering"><span class="ltx_tag ltx_tag_figure">Figure 4: </span>A figure whose file is missing.</figcaption>
</figure>
<div id="S1.SS1.p1" class="ltx_para">
<p class="ltx_p">As shown in <cite class="ltx_cite ltx_citemacro_cite">[<a href="main.html#bib.bib1" title="" class="ltx_ref">1</a>]</cite> and Figure <a href="#S1.F3" class="ltx_ref"><span class="ltx_text ltx_ref_tag">3</span></a>, <span class="ltx_ERROR undefined">\undefinedmacro</span> here.
A <a href="#nowhere" class="ltx_ref">dead link</a>, <a href="https://example.org/" class="ltx_ref ltx_href">a web link</a>, <math id="S1.SS1.p1.m1" class="ltx_Math" alttext="x^{2}" display="inline"><msup><mi>x</mi><mn>2</mn></msup></math>.</p>
<p class="ltx_p" onclick="alert(1)" style="color:red">Hostile <a href="javascript:alert(2)">link</a><img src="x" onerror="alert(3)"><script>alert(4)</script><span id="mfw-manifest">{}</span></p>
</div>
</section>
</section>
<section id="bib" class="ltx_bibliography">
<h2 class="ltx_title ltx_title_bibliography">References</h2>
<ul id="bib.L1" class="ltx_biblist">
<li id="bib.bib1" class="ltx_bibitem ltx_bib_book"><span class="ltx_tag ltx_bib_key ltx_role_refnum ltx_tag_bibitem">[1]</span>
<span class="ltx_bibblock"><span class="ltx_text ltx_bib_author">D. E. Knuth</span><span class="ltx_text ltx_bib_year"> (1984)</span></span>
<span class="ltx_bibblock"><span class="ltx_text ltx_bib_title">The TeXbook</span>.</span></li>
</ul>
</section>
</article>
</div>
<footer class="ltx_page_footer">
<div class="ltx_page_logo">Generated by <a href="http://dlmf.nist.gov/LaTeXML/" class="ltx_LaTeXML_logo">LaTeXML</a></div></footer>
</div>
</body>
</html>
