//! Paper bundle export: a compiled main file, its widgets and its assets
//! written as the layout of `notes/interactive-papers/2026-09-25-bundle-spec.md`
//! to a destination outside the project root.
//!
//! The export reads project files and the compiled output; it never fetches.
//! A remote asset with no local copy would need a download to be hashed, and
//! that download is refused unless the user approved that exact url for this
//! export. The approval is an argument of [`export_bundle_with`] that only
//! the app's own user action can set; the automation surface calls
//! [`export_bundle`], which takes none.
//!
//! Everything is read, hashed and checked before anything is written, and the
//! bundle is assembled in a sibling staging folder and moved into place, so a
//! refusal or a failure leaves no half-written destination.
//!
//! Widgets are folded into one inline document each in every profile (the
//! 2026-09-30 browser export spike): see [`fold`].
//!
//! A custom runtime widget exports live only when its project copy
//! (`runtimes/<ref>/`) is valid, binds, and is approved; otherwise it
//! exports as its poster with a note, and the export says why. The export
//! never asks: it judges and falls back. The browser preview runs custom
//! runtimes without the approval gate, as it does html widgets.

mod flags;
pub(crate) mod fold;
mod reader;

use crate::reflow;
use crate::widgets::poster::PosterSource;
use crate::widgets::{Widget, WidgetRect, WidgetSource, WidgetType};
use crate::Core;

pub use maleficium_events::BundleProfile;

use base64::Engine;
use serde::{Deserialize, Serialize};
use serde_json::{json, Map, Value};
use sha2::{Digest, Sha256};
use std::collections::{BTreeMap, BTreeSet};
use std::io::{Read, Write};
use std::path::{Path, PathBuf};
use ts_rs::TS;

/// The committed manifest schema (JSON Schema 2020-12); the bundle spec
/// points here.
pub const MANIFEST_SCHEMA: &str = include_str!("../schemas/paper-bundle-1.schema.json");

/// The single-file profile warns above this many bytes unless the caller
/// configures another cap.
pub const DEFAULT_SIZE_CAP_BYTES: u64 = 50 * 1024 * 1024;

const FORMAT: &str = "maleficium-paper-bundle";
const CONTRACT_VERSION: u32 = 1;
/// Built-in runtime hosts, generated by `npm run build:runtimes`.
const TABLE_HOST: &str = include_str!("../../widget-runtimes/table/index.html");
const CHART_HOST: &str = include_str!("../../widget-runtimes/chart/index.html");
const MODEL_HOST: &str = include_str!("../../widget-runtimes/model/index.html");
const VIDEO_HOST: &str = include_str!("../../widget-runtimes/video/index.html");

/// Downloads one url for an approved export. Core has no implementation: the
/// app does not fetch on its own.
pub trait Fetcher {
    fn fetch(&self, url: &str) -> Result<Vec<u8>, String>;
}

/// What one export is allowed to do beyond reading the project.
#[derive(Default)]
pub struct BundleOptions<'a> {
    /// Single-file warning threshold; [`DEFAULT_SIZE_CAP_BYTES`] when absent.
    pub size_cap_bytes: Option<u64>,
    /// Urls the user approved fetching, for this export only.
    pub approved_fetch: &'a [String],
    /// Who fetches an approved url.
    pub fetcher: Option<&'a dyn Fetcher>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, schemars::JsonSchema, TS)]
#[serde(rename_all = "kebab-case")]
pub enum BundleWarningKind {
    /// The single-file output is larger than its cap.
    SizeCap,
    /// Files of an author bundle that nothing inlined and so cannot load.
    UnfoldedFiles,
    /// An author bundle references another origin.
    ExternalReference,
    /// Another folding limit (module imports, css `@import`, oversized file).
    FoldLimit,
    /// Paper metadata the export could not read from the source.
    Metadata,
    /// The conversion to HTML reported errors (its log, or raw TeX latexml
    /// left inline); the article was still produced.
    Conversion,
    /// The article's widget placeholders and the compile's widget sidecar
    /// disagree; the widgets are listed at the end of the article.
    WidgetJoin,
    /// A figure the article shows as a placeholder (missing, outside the
    /// main file's folder, EPS, too large).
    Figure,
    /// A custom runtime's widgets export as posters only (not installed,
    /// invalid, not approved or denied); one warning per runtime.
    Runtime,
    /// A custom widget's cached poster was rendered for an older state of
    /// its runtime: the export shows a placeholder until the next compile
    /// renders it. Never refused.
    RuntimeDigestChanged,
    /// The author's reader stylesheet was refused (a remote or escaping
    /// url(), @import, or script); the page keeps the theme alone.
    ReaderStyle,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, schemars::JsonSchema, TS)]
pub struct BundleWarning {
    pub kind: BundleWarningKind,
    pub message: String,
}

/// What an export wrote.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, schemars::JsonSchema, TS)]
#[serde(rename_all = "camelCase")]
pub struct BundleExported {
    /// The folder (folder, hosted) or the file (single-file) written.
    pub path: String,
    pub profile: BundleProfile,
    /// Total bytes written.
    pub bytes: u64,
    pub widgets: u32,
    pub assets: u32,
    pub warnings: Vec<BundleWarning>,
}

/// One heading anchor of the in-app article, in document order.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct ArticleAnchor {
    pub id: String,
    pub text: String,
}

/// The in-app article: the single-file reader page's bytes (its own CSP
/// meta intact) with unapproved html widgets held back, plus the heading
/// anchors the editor-to-article sync scrolls to.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct ArticleView {
    pub html: String,
    pub anchors: Vec<ArticleAnchor>,
}

#[derive(Clone, Copy, PartialEq, Eq)]
enum Mode {
    Bundled,
    Inline,
    Remote,
}

impl Mode {
    fn name(self) -> &'static str {
        match self {
            Mode::Bundled => "bundled",
            Mode::Inline => "inline",
            Mode::Remote => "remote",
        }
    }
}

/// Where an asset's bytes come from at write time.
enum Bytes {
    File(PathBuf),
    Mem(Vec<u8>),
    /// A remote asset: nothing is stored.
    None,
}

struct Asset {
    mode: Mode,
    sha: String,
    bytes: u64,
    mime: String,
    ext: String,
    source: Option<String>,
    url: Option<String>,
    data: Bytes,
}

impl Asset {
    fn path(&self) -> String {
        format!("assets/{}.{}", self.sha, self.ext)
    }

    fn record(&self) -> Value {
        let mut o = Map::new();
        o.insert("mode".into(), self.mode.name().into());
        match self.mode {
            Mode::Bundled => {
                o.insert("path".into(), self.path().into());
            }
            Mode::Inline => {
                o.insert("path".into(), Value::Null);
            }
            Mode::Remote => {
                o.insert("url".into(), self.url.clone().into());
            }
        }
        o.insert("sha256".into(), self.sha.clone().into());
        o.insert("bytes".into(), self.bytes.into());
        o.insert("mime".into(), self.mime.clone().into());
        if let Some(s) = &self.source {
            o.insert("source".into(), s.clone().into());
        }
        Value::Object(o)
    }
}

/// One widget as the manifest records it, and its folded document (none
/// for a custom widget that falls back to its poster).
struct Planned {
    json: Value,
    id: String,
    doc: Option<String>,
    /// The frame origins this widget declared (empty for runtime widgets).
    frames: Vec<String>,
}

fn hex(bytes: &[u8]) -> String {
    use std::fmt::Write as _;
    bytes.iter().fold(String::new(), |mut s, b| {
        let _ = write!(s, "{b:02x}");
        s
    })
}

pub(crate) fn sha_of(bytes: &[u8]) -> String {
    hex(&Sha256::digest(bytes))
}

/// Streams a file through sha256: its digest and length.
fn hash_file(path: &Path) -> Result<(String, u64), String> {
    let mut f =
        std::fs::File::open(path).map_err(|e| format!("cannot read {}: {e}", path.display()))?;
    let mut h = Sha256::new();
    let mut buf = vec![0u8; 1 << 20];
    let mut n_total = 0u64;
    loop {
        let n = f
            .read(&mut buf)
            .map_err(|e| format!("cannot read {}: {e}", path.display()))?;
        if n == 0 {
            break;
        }
        h.update(&buf[..n]);
        n_total += n as u64;
    }
    Ok((hex(&h.finalize()), n_total))
}

/// A file extension safe for the `assets/<sha256>.<ext>` pattern.
fn safe_ext(path: &str) -> String {
    let ext: String = Path::new(path)
        .extension()
        .and_then(|e| e.to_str())
        .unwrap_or("")
        .to_ascii_lowercase()
        .chars()
        .filter(char::is_ascii_alphanumeric)
        .collect();
    if ext.is_empty() {
        "bin".to_string()
    } else {
        ext
    }
}

fn truthy(v: &str) -> bool {
    matches!(v.trim().to_ascii_lowercase().as_str(), "true" | "1" | "yes")
}

fn option<'a>(w: &'a Widget, key: &str) -> Option<&'a str> {
    w.options
        .iter()
        .find(|o| o.key == key)
        .map(|o| o.value.as_str())
}

// ---- paper metadata -----------------------------------------------------

/// The text of the brace group that starts at `s[i]` (a `{`), and the index
/// after its closing brace.
fn brace_group(s: &str, i: usize) -> Option<(String, usize)> {
    let b = s.as_bytes();
    if b.get(i) != Some(&b'{') {
        return None;
    }
    let mut depth = 0usize;
    let mut j = i;
    while j < b.len() {
        match b[j] {
            b'\\' => j += 1,
            b'{' => depth += 1,
            b'}' => {
                depth -= 1;
                if depth == 0 {
                    return Some((s[i + 1..j].to_string(), j + 1));
                }
            }
            _ => {}
        }
        j += 1;
    }
    None
}

fn strip_comments(tex: &str) -> String {
    tex.lines()
        .map(|l| {
            let b = l.as_bytes();
            let mut i = 0;
            while i < b.len() {
                if b[i] == b'\\' {
                    i += 2;
                    continue;
                }
                if b[i] == b'%' {
                    return &l[..i];
                }
                i += 1;
            }
            l
        })
        .collect::<Vec<_>>()
        .join("\n")
}

/// The first `\name{...}` (with an optional `[..]`) in `tex`.
fn command_arg(tex: &str, name: &str) -> Option<String> {
    let needle = format!("\\{name}");
    let mut from = 0;
    while let Some(p) = tex[from..].find(&needle) {
        let mut i = from + p + needle.len();
        from = i;
        let next = tex[i..].chars().next();
        if next.is_some_and(|c| c.is_ascii_alphabetic()) {
            continue;
        }
        let rest = tex[i..].trim_start();
        i = tex.len() - rest.len();
        let mut j = i;
        if tex[j..].starts_with('[') {
            match tex[j..].find(']') {
                Some(e) => j += e + 1,
                None => continue,
            }
            j = tex.len() - tex[j..].trim_start().len();
        }
        if let Some((g, _)) = brace_group(tex, j) {
            return Some(g);
        }
    }
    None
}

/// Plain text of a small LaTeX fragment: footnote-like groups dropped, `\\`
/// and `~` as spaces, other commands reduced to their argument.
fn plain(s: &str) -> String {
    let mut s = s.to_string();
    for drop in ["thanks", "footnote", "label"] {
        let needle = format!("\\{drop}");
        while let Some(p) = s.find(&needle) {
            let rest = &s[p + needle.len()..];
            let off = rest.len() - rest.trim_start().len();
            match brace_group(&s, p + needle.len() + off) {
                Some((_, end)) => s.replace_range(p..end, ""),
                None => s.replace_range(p..p + needle.len(), ""),
            }
        }
    }
    let s = s.replace("\\\\", " ").replace("\\&", "&").replace('~', " ");
    let cmd = regex::Regex::new(r"\\[A-Za-z]+\*?").unwrap();
    let s = cmd.replace_all(&s, "");
    let s: String = s.chars().filter(|c| *c != '{' && *c != '}').collect();
    s.split_whitespace().collect::<Vec<_>>().join(" ")
}

struct Meta {
    title: String,
    authors: Vec<(String, Vec<String>)>,
    abstract_text: Option<String>,
}

/// Title, authors and abstract of the main file, as far as its own preamble
/// and body say. Anything unreadable gets a named default and a warning.
fn paper_meta(tex: &str, stem: &str, warnings: &mut Vec<BundleWarning>) -> Meta {
    let tex = strip_comments(tex);
    let mut warn = |m: String| {
        warnings.push(BundleWarning {
            kind: BundleWarningKind::Metadata,
            message: m,
        })
    };
    let title = command_arg(&tex, "title")
        .map(|t| plain(&t))
        .filter(|t| !t.is_empty());
    let title = title.unwrap_or_else(|| {
        warn(format!(
            "the main file has no \\title: the manifest title is the file name `{stem}`"
        ));
        stem.to_string()
    });
    let mut authors: Vec<(String, Vec<String>)> = Vec::new();
    if let Some(a) = command_arg(&tex, "author") {
        let split = regex::Regex::new(r"\\(?:and|And|AND)\b").unwrap();
        for part in split.split(&a) {
            let lines: Vec<String> = part
                .split("\\\\")
                .map(plain)
                .filter(|l| !l.is_empty())
                .collect();
            if let Some((name, aff)) = lines.split_first() {
                authors.push((name.clone(), aff.to_vec()));
            }
        }
    }
    if authors.is_empty() {
        warn(
            "the main file has no \\author: the manifest lists one author with an empty name"
                .to_string(),
        );
        authors.push((String::new(), Vec::new()));
    }
    let abstract_text = tex
        .find("\\begin{abstract}")
        .and_then(|s| {
            let body = &tex[s + "\\begin{abstract}".len()..];
            body.find("\\end{abstract}").map(|e| plain(&body[..e]))
        })
        .filter(|a| !a.is_empty());
    Meta {
        title,
        authors,
        abstract_text,
    }
}

/// The directories of the main file's `\graphicspath{{a/}{b/}}`, in order.
fn graphics_paths(tex: &str) -> Vec<String> {
    let tex = strip_comments(tex);
    let Some(arg) = command_arg(&tex, "graphicspath") else {
        return Vec::new();
    };
    let mut out = Vec::new();
    let mut i = 0;
    while let Some(off) = arg[i..].find('{') {
        match brace_group(&arg, i + off) {
            Some((dir, end)) => {
                out.push(dir.trim().to_string());
                i = end;
            }
            None => break,
        }
    }
    out
}

// ---- the planner --------------------------------------------------------

struct Plan<'a> {
    cx: &'a Core,
    root_id: &'a str,
    main_rel: &'a str,
    root: PathBuf,
    main_dir_rel: PathBuf,
    profile: BundleProfile,
    opts: &'a BundleOptions<'a>,
    /// The paper's theme: posters are keyed by it.
    theme: &'a crate::theme::Theme,
    assets: BTreeMap<String, Asset>,
    warnings: Vec<BundleWarning>,
    /// Whether custom runtimes are judged (export) or not (preview).
    gate: Gate<'a>,
    /// The widgets using each custom runtime, in document order.
    users: BTreeMap<String, Vec<String>>,
    /// Each custom runtime read and judged once per export.
    runtimes: BTreeMap<String, std::rc::Rc<RuntimeUse>>,
    /// The manifest's `runtimes` map: every runtime a live widget runs.
    runtime_entries: Map<String, Value>,
    /// Custom widgets that fall back to their posters, by runtime: why, and
    /// which widgets.
    fallbacks: BTreeMap<String, (Fallback, Vec<String>)>,
    /// Whether a live custom widget declares `capabilities.wasm`: a
    /// single-file bundle srcdocs its widgets, so the reader page inherits
    /// down and must carry the token too (its own frame-src union's
    /// companion).
    wasm_live: bool,
    /// The note a fallback widget's figure carries, by widget id.
    notes: BTreeMap<String, String>,
    /// Html widgets the in-app article holds back for approval, by widget
    /// id. Exports and the browser preview never gate html widgets; the
    /// article view does.
    gated: BTreeSet<String>,
}

/// Whether an export judges custom runtimes against the approval store at
/// this base, runs them unjudged (the browser preview, as html widgets), or
/// renders the in-app article (judged runtimes, plus html widgets held back
/// for approval).
#[derive(Clone, Copy)]
enum Gate<'a> {
    Approvals(&'a Path),
    Preview,
    Article(&'a Path),
}

/// Why a custom widget exports as its poster.
#[derive(Debug, Clone, PartialEq, Eq)]
enum Fallback {
    Missing,
    Invalid(String),
    Unapproved,
    Denied,
}

impl Fallback {
    /// The manifest's `fallback` value.
    fn name(&self) -> &'static str {
        match self {
            Fallback::Missing => "runtime-missing",
            Fallback::Invalid(_) => "runtime-invalid",
            Fallback::Unapproved => "unapproved",
            Fallback::Denied => "denied",
        }
    }

    /// The note under the poster.
    fn note(&self, r: &str) -> String {
        let why = match self {
            Fallback::Missing => "is not installed",
            Fallback::Invalid(_) => "did not pass validation",
            Fallback::Unapproved | Fallback::Denied => "was not approved by the author",
        };
        format!("Interactive version not included in this copy: runtime {r} {why}.")
    }

    /// The export warning for the runtime and the widgets it affects.
    fn warning(&self, r: &str, ids: &str) -> String {
        match self {
            Fallback::Missing => format!(
                "runtime {r} is not installed in this project (no {}/{r}/{}): {ids} export as posters only.",
                crate::runtimes::RUNTIMES_DIR,
                crate::runtimes::MANIFEST
            ),
            Fallback::Invalid(reason) => {
                format!("runtime {r} is invalid ({reason}): {ids} export as posters only.")
            }
            Fallback::Unapproved => format!(
                "runtime {r} is not approved in this project: {ids} export as posters only. Approve it in {} and export again.",
                crate::widget_approval::PANEL
            ),
            Fallback::Denied => format!(
                "runtime {r} is denied in this project: {ids} export as posters only. Allow it in {} to export it live.",
                crate::widget_approval::PANEL
            ),
        }
    }
}

/// A custom runtime as this export found it.
enum RuntimeUse {
    Unusable(Fallback),
    Valid(Box<ValidRuntime>),
}

/// A valid package: the snapshot that was hashed (and judged), its
/// manifest, and why its widgets do not run live, if they do not.
struct ValidRuntime {
    snap: crate::widget_approval::RuntimeSnapshot,
    manifest: crate::runtimes::RuntimeManifest,
    verdict: Option<Fallback>,
}

/// A custom widget's folded document and bound options, both absent when
/// it falls back to its poster.
type CustomPlan = (Option<String>, Option<Map<String, Value>>);

impl Plan<'_> {
    fn warn(&mut self, kind: BundleWarningKind, message: String) {
        self.warnings.push(BundleWarning { kind, message });
    }

    /// Runtime `r` read once for this export, judged unless previewing.
    fn runtime(&mut self, r: &str) -> Result<std::rc::Rc<RuntimeUse>, String> {
        if let Some(u) = self.runtimes.get(r) {
            return Ok(u.clone());
        }
        let users = self.users.get(r).cloned().unwrap_or_default();
        let checked = match self.gate {
            Gate::Approvals(base) | Gate::Article(base) => {
                crate::widget_approval::check_runtime_at(base, self.cx, self.root_id, r, &users)
                    .map(|c| (c.snapshot, c.status))
            }
            Gate::Preview => crate::widget_approval::snapshot_runtime(self.cx, self.root_id, r)
                .map(|s| (s, None)),
        };
        let used = match checked {
            Err(_) => RuntimeUse::Unusable(Fallback::Missing),
            Ok((snap, status)) => match snap.manifest.clone() {
                None => {
                    let reason = snap.invalid.clone().unwrap_or_default();
                    let reason = reason
                        .strip_prefix(&format!("runtime {r}: "))
                        .map(str::to_string)
                        .unwrap_or(reason);
                    RuntimeUse::Unusable(Fallback::Invalid(reason))
                }
                Some(manifest) => {
                    use crate::widget_approval::WidgetApprovalStatus as S;
                    let verdict = match (self.gate, status) {
                        (Gate::Preview, _) => None,
                        (_, Some(S::Approved(_))) => None,
                        (_, Some(S::ApprovalRequired(a)))
                            if a.cause == maleficium_events::WidgetApprovalCause::Revoked =>
                        {
                            Some(Fallback::Denied)
                        }
                        (_, _) => Some(Fallback::Unapproved),
                    };
                    RuntimeUse::Valid(Box::new(ValidRuntime {
                        snap,
                        manifest,
                        verdict,
                    }))
                }
            },
        };
        let used = std::rc::Rc::new(used);
        self.runtimes.insert(r.to_string(), used.clone());
        Ok(used)
    }

    fn fall_back(&mut self, r: &str, id: &str, why: Fallback) {
        self.notes.insert(id.to_string(), why.note(r));
        self.fallbacks
            .entry(r.to_string())
            .or_insert_with(|| (why, Vec::new()))
            .1
            .push(id.to_string());
    }

    /// A project file named relative to the main file's folder: resolved
    /// inside the root (symlinks that escape are refused) and a regular file.
    fn local(&self, widget: &str, rel: &str) -> Result<(PathBuf, String), String> {
        let joined = self.main_dir_rel.join(rel);
        let canon = crate::fs::resolve_in(self.cx, self.root_id, &joined.to_string_lossy())
            .map_err(|e| format!("widget {widget}: {rel}: {e}"))?;
        if !canon.is_file() {
            return Err(format!("widget {widget}: {rel} is not a file"));
        }
        let source = canon
            .strip_prefix(&self.root)
            .map_err(|_| format!("widget {widget}: {rel} is outside the project"))?
            .to_string_lossy()
            .replace('\\', "/");
        Ok((canon, source))
    }

    fn mode_for(&self, inline_opt: bool) -> Mode {
        if self.profile == BundleProfile::SingleFile || inline_opt {
            Mode::Inline
        } else {
            Mode::Bundled
        }
    }

    fn insert(&mut self, key: String, a: Asset) -> Result<(), String> {
        if self.assets.insert(key.clone(), a).is_some() {
            return Err(format!("two assets would be keyed `{key}`"));
        }
        Ok(())
    }

    fn add_local(
        &mut self,
        key: String,
        widget: &str,
        rel: &str,
        inline_opt: bool,
    ) -> Result<(), String> {
        let (canon, source) = self.local(widget, rel)?;
        let (sha, bytes) = hash_file(&canon)?;
        let ext = safe_ext(rel);
        let a = Asset {
            mode: self.mode_for(inline_opt),
            mime: fold::mime_for(&ext).to_string(),
            sha,
            bytes,
            ext,
            source: Some(source),
            url: None,
            data: Bytes::File(canon),
        };
        self.insert(key, a)
    }

    fn add_mem(
        &mut self,
        key: String,
        ext: &str,
        data: Vec<u8>,
        inline_opt: bool,
    ) -> Result<(), String> {
        let a = Asset {
            mode: self.mode_for(inline_opt),
            mime: fold::mime_for(ext).to_string(),
            sha: sha_of(&data),
            bytes: data.len() as u64,
            ext: ext.to_string(),
            source: None,
            url: None,
            data: Bytes::Mem(data),
        };
        self.insert(key, a)
    }

    /// A remote asset: hashed from the local copy when there is one. With no
    /// local copy the hash needs a download, which is refused unless this
    /// export carries the user's approval for that url.
    fn add_remote(
        &mut self,
        key: String,
        widget: &str,
        role: &str,
        url: &str,
        local: Option<&str>,
        declared_sha: Option<&str>,
    ) -> Result<(), String> {
        if !url.starts_with("https://") || url.len() < 9 {
            return Err(format!(
                "widget {widget}: remote asset {role} must be an https url, not `{url}`"
            ));
        }
        let ext = safe_ext(url.split(['?', '#']).next().unwrap_or(url));
        let (sha, bytes, source) = match local {
            Some(rel) => {
                let (canon, source) = self.local(widget, rel)?;
                let (sha, bytes) = hash_file(&canon)?;
                (sha, bytes, Some(source))
            }
            None => {
                if !self.opts.approved_fetch.iter().any(|u| u == url) {
                    return Err(format!(
                        "widget {widget}: remote asset {role} ({url}) has no local copy, so hashing it needs a download. Maleficium does not fetch on its own: the user has to approve downloading that url for this export, and an agent cannot grant it. Put a local copy of the file next to the paper, or approve the download in the app."
                    ));
                }
                let Some(f) = self.opts.fetcher else {
                    return Err(format!(
                        "widget {widget}: remote asset {role} ({url}) was approved for download, but this build has no downloader"
                    ));
                };
                let data = f.fetch(url)?;
                (sha_of(&data), data.len() as u64, None)
            }
        };
        if let Some(d) = declared_sha {
            if !d.eq_ignore_ascii_case(&sha) {
                return Err(format!(
                    "widget {widget}: sha256 {d} does not match the {role} file (computed {sha})"
                ));
            }
        }
        let a = Asset {
            mode: Mode::Remote,
            mime: fold::mime_for(&ext).to_string(),
            sha,
            bytes,
            ext,
            source,
            url: Some(url.to_string()),
            data: Bytes::None,
        };
        self.insert(key, a)
    }
}

fn json_number_or_string(v: &str) -> Value {
    if !v.is_empty() && v.len() < 15 && v.bytes().all(|c| c.is_ascii_digit()) {
        v.parse::<u64>().map_or_else(|_| v.into(), Value::from)
    } else {
        v.into()
    }
}

/// The rendered region of a page, as a PNG: what a table's typeset rows look
/// like in the pdf of record.
fn crop_png(pdf: &hayro::hayro_syntax::Pdf, page: u32, r: &WidgetRect) -> Result<Vec<u8>, String> {
    use hayro::vello_cpu::color::palette::css::WHITE;
    use hayro::vello_cpu::Pixmap;
    std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let p = &pdf.pages()[page as usize - 1];
        let (_, page_h) = p.render_dimensions();
        let width_pt = ((r.x1 - r.x0) as f32).max(1.0);
        let scale = 2.0f32.min(1600.0 / width_pt);
        let settings = hayro::RenderSettings {
            x_scale: scale,
            y_scale: scale,
            bg_color: WHITE,
            ..Default::default()
        };
        let full = hayro::render(
            p,
            &hayro::RenderCache::new(),
            &hayro::hayro_interpret::InterpreterSettings::default(),
            &settings,
        );
        let (w, h) = (full.width() as usize, full.height() as usize);
        let px = |v: f32, hi: usize| ((v * scale).max(0.0) as usize).min(hi);
        let (x0, x1) = (
            px(r.x0 as f32, w),
            (((r.x1 as f32) * scale).ceil() as usize).min(w),
        );
        let (y0, y1) = (
            px(page_h - r.y1 as f32, h),
            (((page_h - r.y0 as f32) * scale).ceil() as usize).min(h),
        );
        if x1 <= x0 || y1 <= y0 {
            return Err(format!("the widget's rect lies outside page {page}"));
        }
        let mut buf = Vec::with_capacity((x1 - x0) * (y1 - y0));
        for row in y0..y1 {
            buf.extend_from_slice(&full.data()[row * w + x0..row * w + x1]);
        }
        Pixmap::from_parts(buf, (x1 - x0) as u16, (y1 - y0) as u16)
            .into_png()
            .map_err(|e| format!("cannot encode the table crop: {e}"))
    }))
    .map_err(|_| format!("the renderer failed on page {page}"))?
}

/// The generated host document of a built-in runtime this build ships.
pub(crate) fn runtime_host(runtime: &str) -> Option<&'static str> {
    match runtime {
        "table@1" => Some(TABLE_HOST),
        "chart@1" => Some(CHART_HOST),
        "model@1" => Some(MODEL_HOST),
        "video@1" => Some(VIDEO_HOST),
        _ => None,
    }
}

/// A widget's local sources keyed by role; a repeated role gets `-2`,
/// `-3`, ... in document order.
pub(crate) fn role_keys(w: &Widget) -> Result<Vec<(String, &WidgetSource)>, String> {
    let mut seen: BTreeMap<&str, u32> = BTreeMap::new();
    let mut out = Vec::new();
    for s in &w.sources {
        if s.role.is_empty()
            || !s
                .role
                .bytes()
                .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit())
        {
            return Err(format!(
                "widget {}: source role `{}` is not a plain word",
                w.id, s.role
            ));
        }
        let n = seen.entry(&s.role).or_insert(0);
        *n += 1;
        let key = if *n == 1 {
            s.role.clone()
        } else {
            format!("{}-{}", s.role, n)
        };
        out.push((key, s));
    }
    Ok(out)
}

/// The options a runtime receives: everything but the export-only keys,
/// digits as numbers.
pub(crate) fn runtime_options(w: &Widget) -> Map<String, Value> {
    w.options
        .iter()
        .filter(|o| {
            !matches!(o.key.as_str(), "remote" | "sha256" | "inline")
                && !crate::widgets::ORIGIN_OPTIONS.contains(&o.key.as_str())
        })
        .map(|o| (o.key.clone(), json_number_or_string(&o.value)))
        .collect()
}

/// The licence notice a folded runtime document ends with: the runtime and
/// each vendored library, name, version, licence and licence text, in one
/// HTML comment that no text can close (every `--` is split).
fn licence_block(
    m: &crate::runtimes::RuntimeManifest,
    files: &BTreeMap<String, Vec<u8>>,
) -> String {
    let text = |p: &str| {
        files
            .get(p)
            .map(|b| String::from_utf8_lossy(b).into_owned())
            .unwrap_or_default()
    };
    let mut body = format!(
        "\n{} {} ({})\n{}",
        m.name,
        m.version,
        m.license,
        text("LICENSE")
    );
    for v in &m.vendored {
        body.push_str(&format!(
            "\n{} {} ({})\n{}",
            v.name,
            v.version,
            v.license,
            text(&v.license_file)
        ));
    }
    let mut safe = String::with_capacity(body.len());
    for c in body.chars() {
        if c == '-' && safe.ends_with('-') {
            safe.push(' ');
        }
        safe.push(c);
    }
    format!("<!-- Licences:{safe} -->")
}

/// A custom widget with no usable poster whose map still names one: its
/// poster was rendered for an older state (often a changed runtime
/// digest). The export keeps the placeholder and says so; it never refuses.
fn stale_custom_poster(p: &Plan, w: &Widget) -> Option<String> {
    use crate::widgets::poster::cache::{custom_key_now_at, map_key_for};
    let base = match p.gate {
        Gate::Approvals(base) | Gate::Article(base) => base,
        Gate::Preview => return None,
    };
    let r = w.runtime.as_deref().unwrap_or("");
    let mapped = map_key_for(p.cx, p.root_id, p.main_rel, &w.id)?;
    let (now, _) = custom_key_now_at(base, p.cx, p.root_id, p.main_rel, w, p.theme)?;
    (mapped != now).then(|| {
        format!(
            "widget {}: its poster was rendered for an older state of runtime {r}; it shows a placeholder until the next compile renders it.",
            w.id
        )
    })
}

/// A custom widget: its runtime read and judged once per export, bound
/// (an error refuses the export), then folded live with its sources, or
/// left to its poster with a note. Returns the document and the bound
/// options when live.
fn plan_custom(
    p: &mut Plan,
    w: &Widget,
    sources: &mut Map<String, Value>,
) -> Result<CustomPlan, String> {
    let id = w.id.clone();
    let r = w.runtime.clone().unwrap_or_default();
    let used = p.runtime(&r)?;
    let (snap, m, verdict) = match &*used {
        RuntimeUse::Unusable(why) => {
            p.fall_back(&r, &id, why.clone());
            return Ok((None, None));
        }
        RuntimeUse::Valid(v) => (&v.snap, &v.manifest, &v.verdict),
    };
    let bound = crate::runtimes::bind(w, m)?;
    if let Some(why) = verdict {
        p.fall_back(&r, &id, why.clone());
        return Ok((None, None));
    }
    // A live declaring widget runs srcdoc'd under the single-file reader
    // page: the page's own policy must carry the token, or the inherited
    // one blocks the compile. Folder widgets are documents of their own.
    if m.capabilities.wasm {
        p.wasm_live = true;
    }
    for (role, s) in &bound.sources {
        let key = format!("{id}-{role}");
        p.add_local(key.clone(), &id, &s.path, false)?;
        let bytes = p.assets.get(&key).map_or(0, |a| a.bytes);
        crate::runtimes::check_size(w, m, role, bytes)?;
        sources.insert(role.clone(), key.into());
    }
    // The judged snapshot's files, never a second read of the folder,
    // folded with the runtime's own policy: only a runtime that declared
    // capabilities.wasm carries 'wasm-unsafe-eval'.
    let fold_input: BTreeMap<String, Vec<u8>> = snap
        .files
        .iter()
        .filter(|(path, _)| !m.is_metadata(path))
        .map(|(k, v)| (k.clone(), v.clone()))
        .collect();
    let folded = fold::fold_bundle(
        &fold_input,
        &fold::widget_policy_for(None, m.capabilities.wasm),
    )
    .map_err(|e| format!("widget {id}: runtime {r}: {e}"))?;
    if !folded.unfolded.is_empty() {
        let shown: Vec<_> = folded.unfolded.iter().take(8).cloned().collect();
        let more = folded.unfolded.len() - shown.len();
        p.warn(
            BundleWarningKind::UnfoldedFiles,
            format!(
                "widget {id}: runtime {r} files not inlined, so a page that fetches them at run time will not find them: {}{}",
                shown.join(", "),
                if more > 0 { format!(" and {more} more") } else { String::new() }
            ),
        );
    }
    for e in &folded.external {
        p.warn(
            BundleWarningKind::ExternalReference,
            format!("widget {id}: runtime {r} references {e}, which its policy blocks"),
        );
    }
    for n in &folded.notes {
        p.warn(
            BundleWarningKind::FoldLimit,
            format!("widget {id}: runtime {r}: {n}"),
        );
    }
    let doc = folded.html + &licence_block(m, &snap.files);
    p.runtime_entries.insert(
        r.clone(),
        json!({
            "name": m.name,
            "version": m.version,
            "digest": snap.digest,
            "license": m.license,
            "capabilities": { "webgl": m.capabilities.webgl, "wasm": m.capabilities.wasm },
            "vendored": m.vendored.iter().map(|v| json!({
                "name": v.name, "version": v.version, "license": v.license
            })).collect::<Vec<_>>(),
        }),
    );
    Ok((Some(doc), Some(bound.options)))
}

fn plan_widget(
    p: &mut Plan,
    w: &Widget,
    pdf: &hayro::hayro_syntax::Pdf,
    pdf_pages: u32,
) -> Result<Planned, String> {
    let id = w.id.clone();
    if w.page < 1 || w.page > pdf_pages {
        return Err(format!(
            "widget {id}: page {} is outside the pdf's {pdf_pages} pages",
            w.page
        ));
    }
    let mb = pdf.pages()[w.page as usize - 1].media_box();
    let slack = 1.0;
    if w.rect.x0 >= w.rect.x1
        || w.rect.y0 >= w.rect.y1
        || w.rect.x0 < mb.x0 - slack
        || w.rect.y0 < mb.y0 - slack
        || w.rect.x1 > mb.x1 + slack
        || w.rect.y1 > mb.y1 + slack
    {
        return Err(format!(
            "widget {id}: its rect lies outside the media box of page {}",
            w.page
        ));
    }
    let inline_opt = option(w, "inline").is_some_and(truthy);
    let remote = option(w, "remote").filter(|r| !r.is_empty());
    if remote.is_some() && w.kind != WidgetType::Video {
        return Err(format!(
            "widget {id}: remote= is only supported on video widgets"
        ));
    }

    // The poster is what the pdf shows: the document's own, else the
    // cached auto-poster, else (a table's typeset rows, a placeholder)
    // cropped from the pdf. The cache is read against the same approval
    // store the export judges runtimes by, so an isolated store (tests,
    // the article) sees its own posters.
    let poster_key = format!("{id}-poster");
    let cached = match p.gate {
        Gate::Approvals(base) | Gate::Article(base) => {
            crate::widgets::poster::cache::cached_poster_at(
                base, p.cx, p.root_id, p.main_rel, w, p.theme,
            )
        }
        Gate::Preview => {
            crate::widgets::poster::cache::cached_poster(p.cx, p.root_id, p.main_rel, w, p.theme)
        }
    };
    let source = crate::widgets::poster::poster_source(w, cached.as_deref());
    match source {
        PosterSource::Explicit(rel) if w.kind != WidgetType::Table => {
            p.add_local(poster_key.clone(), &id, &rel, inline_opt)?
        }
        PosterSource::Cached(png) => {
            let name = png.file_name().map(|n| n.to_string_lossy().into_owned());
            let rel = Path::new(crate::widgets::poster::cache::CACHE_DIR)
                .join(crate::widgets::poster::cache::POSTERS_DIR)
                .join(name.unwrap_or_default());
            p.add_local(poster_key.clone(), &id, &rel.to_string_lossy(), inline_opt)?
        }
        _ => {
            if w.kind == WidgetType::Custom {
                if let Some(msg) = stale_custom_poster(p, w) {
                    p.warn(BundleWarningKind::RuntimeDigestChanged, msg);
                }
            }
            let png = crop_png(pdf, w.page, &w.rect).map_err(|e| format!("widget {id}: {e}"))?;
            p.add_mem(poster_key.clone(), "png", png, inline_opt)?;
        }
    }

    let mut sources = Map::new();
    // A widget's declared origins come from the snapshot whose files are
    // folded, never from an earlier read: the policy and the code match.
    let mut csp: Option<crate::widgets::WidgetCsp> = None;
    // A live custom widget's bound options.
    let mut custom_options: Option<Map<String, Value>> = None;

    let doc: Option<String> = if w.kind == WidgetType::Html {
        let target = crate::widget_approval::WidgetTarget::of(p.main_rel, w)?
            .ok_or_else(|| format!("widget {id}: an html widget has no bundle folder"))?;
        let snap = crate::widget_approval::snapshot(p.cx, p.root_id, &target)?;
        csp = (!snap.origins.is_empty()).then(|| snap.origins.clone());
        let policy = fold::widget_policy(csp.as_ref());
        let folded =
            fold::fold_bundle(&snap.files, &policy).map_err(|e| format!("widget {id}: {e}"))?;
        if !folded.unfolded.is_empty() {
            let shown: Vec<_> = folded.unfolded.iter().take(8).cloned().collect();
            let more = folded.unfolded.len() - shown.len();
            p.warn(
                BundleWarningKind::UnfoldedFiles,
                format!(
                    "widget {id}: files not inlined, so a page that fetches them at run time will not find them: {}{}",
                    shown.join(", "),
                    if more > 0 { format!(" and {more} more") } else { String::new() }
                ),
            );
        }
        for e in &folded.external {
            p.warn(
                BundleWarningKind::ExternalReference,
                format!("widget {id}: references {e}, which its policy blocks unless widget.json declares the origin"),
            );
        }
        for n in &folded.notes {
            p.warn(BundleWarningKind::FoldLimit, format!("widget {id}: {n}"));
        }
        // The in-app article holds back what the user has not approved: the
        // figure keeps its poster with an approval affordance, and the folded
        // document is left out. Exports and the browser preview run it.
        let held_back = match p.gate {
            Gate::Article(base) => crate::widget_approval::check_at(base, p.cx, p.root_id, &target)
                .map(|c| !c.status.is_approved())
                .unwrap_or(true),
            _ => false,
        };
        if held_back {
            p.notes.insert(
                id.clone(),
                "This interactive figure needs your approval before it runs here.".to_string(),
            );
            p.gated.insert(id.clone());
            None
        } else {
            Some(folded.html)
        }
    } else if w.kind == WidgetType::Custom {
        let (doc, options) = plan_custom(p, w, &mut sources)?;
        custom_options = options;
        doc
    } else {
        let mut video_local: Option<&str> = None;
        for (role_key, s) in role_keys(w)? {
            if w.kind == WidgetType::Video && s.role == "video" && remote.is_some() {
                video_local = Some(&s.path);
                continue;
            }
            let key = format!("{id}-{role_key}");
            p.add_local(key.clone(), &id, &s.path, inline_opt)?;
            sources.insert(role_key, key.into());
        }
        if let Some(url) = remote {
            let key = format!("{id}-video");
            p.add_remote(
                key.clone(),
                &id,
                "video",
                url,
                video_local,
                option(w, "sha256").filter(|s| !s.is_empty()),
            )?;
            sources.insert("video".into(), key.into());
        }
        let required = match w.kind {
            WidgetType::Model => Some("model"),
            WidgetType::Video => Some("video"),
            WidgetType::Table => Some("data"),
            WidgetType::Chart => Some("spec"),
            WidgetType::Html | WidgetType::Custom => None,
        };
        if let Some(role) = required {
            if !sources.contains_key(role) {
                return Err(format!("widget {id}: it records no {role} source"));
            }
        }
        let runtime = w.runtime.as_deref().unwrap_or("");
        let host = runtime_host(runtime)
            .ok_or_else(|| format!("widget {id}: no {runtime} runtime in this build"))?;
        Some(fold::with_policy(host, &fold::widget_policy(None)))
    };
    let entry = (p.profile != BundleProfile::SingleFile && doc.is_some())
        .then(|| format!("widgets/{id}/index.html"));

    let mut j = Map::new();
    j.insert("id".into(), id.clone().into());
    j.insert(
        "type".into(),
        serde_json::to_value(w.kind).map_err(|e| e.to_string())?,
    );
    if w.kind != WidgetType::Html {
        j.insert("runtime".into(), w.runtime.clone().into());
    }
    if let Some(e) = entry {
        j.insert("entry".into(), e.into());
    }
    j.insert("page".into(), w.page.into());
    j.insert(
        "rect".into(),
        json!([w.rect.x0, w.rect.y0, w.rect.x1, w.rect.y1]),
    );
    if let Some(l) = &w.label {
        j.insert("label".into(), l.clone().into());
    }
    if let Some(f) = &w.figure {
        j.insert("figure".into(), f.clone().into());
    }
    j.insert("poster".into(), poster_key.into());
    j.insert("alt".into(), w.alt.clone().into());
    if w.kind != WidgetType::Html {
        j.insert("sources".into(), Value::Object(sources));
    }
    if w.kind == WidgetType::Custom {
        match custom_options {
            Some(o) => {
                j.insert("options".into(), Value::Object(o));
            }
            None => {
                let r = w.runtime.as_deref().unwrap_or("");
                let why = p.fallbacks.get(r).map_or("", |(f, _)| f.name());
                j.insert("fallback".into(), why.into());
            }
        }
    } else {
        let opts = runtime_options(w);
        if !opts.is_empty() {
            j.insert("options".into(), Value::Object(opts));
        }
    }
    if let Some(c) = &csp {
        j.insert(
            "csp".into(),
            serde_json::to_value(c).map_err(|e| e.to_string())?,
        );
    }
    Ok(Planned {
        json: Value::Object(j),
        id,
        doc,
        frames: csp.map(|c| c.frame_domains).unwrap_or_default(),
    })
}

// ---- the theme ------------------------------------------------------------

fn theme_json(id: &str) -> String {
    let v = json!({
        "id": id,
        "name": "Maleficium house",
        "contractVersion": CONTRACT_VERSION,
        "author": "Maleficium contributors",
        "license": "Apache-2.0",
        "modes": ["light", "dark"],
        "css": ["theme.css"],
        "fonts": []
    });
    serde_json::to_string_pretty(&v).unwrap_or_default() + "\n"
}

// ---- manifest -----------------------------------------------------------

fn validator() -> Result<jsonschema::Validator, String> {
    let schema: Value = serde_json::from_str(MANIFEST_SCHEMA)
        .map_err(|e| format!("the committed manifest schema is not json: {e}"))?;
    jsonschema::validator_for(&schema).map_err(|e| format!("the manifest schema is invalid: {e}"))
}

/// Checks a manifest against the committed schema and the invariants the
/// schema cannot express. Every violation is named.
pub fn validate_manifest(m: &Value) -> Result<(), String> {
    // paper.reader: closed shapes with named errors (the schema repeats
    // them). Absent means a bundle from before flags existed: still valid.
    // A boolean is strict: no number or string coerces to it.
    let reader = &m["paper"]["reader"];
    if !reader.is_null() {
        let obj = reader
            .as_object()
            .ok_or_else(|| "paper.reader is not an object".to_string())?;
        if !obj.get("contents").is_some_and(Value::is_boolean) {
            return Err("paper.reader.contents is not a boolean".to_string());
        }
        if !obj
            .get("measure")
            .and_then(Value::as_str)
            .is_some_and(|s| matches!(s, "narrow" | "default" | "wide"))
        {
            return Err("paper.reader.measure is not narrow, default or wide".to_string());
        }
    }
    let v = validator()?;
    let errors: Vec<String> = v
        .iter_errors(m)
        .map(|e| format!("{} at {}", e, e.instance_path()))
        .collect();
    if !errors.is_empty() {
        return Err(format!(
            "the manifest breaks its schema: {}",
            errors.join("; ")
        ));
    }
    let widgets = m["widgets"].as_array().cloned().unwrap_or_default();
    let assets = m["assets"].as_object().cloned().unwrap_or_default();
    let pages = m["pdf"]["pages"].as_u64().unwrap_or(0);
    let profile = m.get("profile").and_then(Value::as_str).unwrap_or("folder");
    let mut ids = BTreeSet::new();
    let mut last: Option<(u64, f64)> = None;
    for w in &widgets {
        let id = w["id"].as_str().unwrap_or("");
        if !ids.insert(id.to_string()) {
            return Err(format!("widget id `{id}` appears twice"));
        }
        let refs = std::iter::once(w["poster"].as_str()).chain(
            w.get("sources")
                .and_then(Value::as_object)
                .into_iter()
                .flat_map(|s| s.values().map(Value::as_str)),
        );
        for r in refs {
            let r = r.unwrap_or("");
            if !assets.contains_key(r) {
                return Err(format!(
                    "widget {id} names asset `{r}`, which does not exist"
                ));
            }
        }
        let page = w["page"].as_u64().unwrap_or(0);
        if page > pages {
            return Err(format!("widget {id} is on page {page} of {pages}"));
        }
        let r: Vec<f64> = w["rect"]
            .as_array()
            .map(|a| a.iter().filter_map(Value::as_f64).collect())
            .unwrap_or_default();
        if r.len() != 4 || r[0] >= r[2] || r[1] >= r[3] {
            return Err(format!("widget {id} has a rect that is not x0<x1, y0<y1"));
        }
        // Document order: page, then top to bottom.
        let top = r[3];
        if let Some((lp, lt)) = last {
            if page < lp || (page == lp && top > lt) {
                return Err(format!("widget {id} is out of document order"));
            }
        }
        last = Some((page, top));
        if profile == "single-file" && w.get("entry").is_some() {
            return Err(format!("widget {id} has an entry in a single-file bundle"));
        }
    }
    // Custom runtimes: every live widget's runtime is listed and every
    // listed runtime is run by a live widget; a listed runtime's name and
    // major match its ref; a fallback widget carries nothing to run; no
    // custom widget declares origins.
    let runtimes = m["runtimes"].as_object().cloned().unwrap_or_default();
    let mut used = BTreeSet::new();
    for w in widgets.iter().filter(|w| w["type"] == "custom") {
        let id = w["id"].as_str().unwrap_or("");
        let r = w["runtime"].as_str().unwrap_or("");
        if w.get("csp").is_some() {
            return Err(format!("custom widget {id} declares a csp"));
        }
        if w.get("fallback").is_some() {
            let empty = w["sources"].as_object().is_some_and(|s| s.is_empty());
            if !empty || w.get("entry").is_some() || w.get("options").is_some() {
                return Err(format!(
                    "widget {id} falls back to its poster but carries sources, an entry or options"
                ));
            }
        } else if !runtimes.contains_key(r) {
            return Err(format!(
                "widget {id} runs runtime {r}, which the manifest does not list"
            ));
        } else {
            used.insert(r.to_string());
        }
    }
    for (r, e) in &runtimes {
        if !used.contains(r) {
            return Err(format!("runtime {r} is listed but no live widget runs it"));
        }
        let major = e["version"]
            .as_str()
            .and_then(|v| v.split('.').next())
            .unwrap_or("");
        let named = format!("{}@{major}", e["name"].as_str().unwrap_or(""));
        if !crate::runtimes::valid_ref(r) || named != *r {
            return Err(format!(
                "runtime {r} is listed as {named}, or names a reserved runtime"
            ));
        }
    }
    if profile == "single-file" {
        if assets.values().any(|a| a["mode"] == "bundled") {
            return Err("a single-file bundle has a bundled asset".to_string());
        }
        if !m["pdf"]["path"].is_null() {
            return Err("a single-file bundle must inline its pdf".to_string());
        }
    } else if m["pdf"]["path"] != "paper.pdf" {
        return Err("a folder or hosted bundle keeps its pdf at paper.pdf".to_string());
    }
    Ok(())
}

// ---- writing ------------------------------------------------------------

/// Serializes JSON for a `<script type="application/json">` island: `<` is
/// escaped so no string can close the element.
fn island(id: &str, v: &Value) -> String {
    let s = serde_json::to_string(v)
        .unwrap_or_default()
        .replace('<', "\\u003c");
    format!("<script type=\"application/json\" id=\"{id}\">{s}</script>")
}

/// Each widget's mount unit: caption fields from the widget list, and the
/// poster as a bundled path or an inline `data:` url.
fn mounts<'a>(
    list: &'a [Widget],
    assets: &BTreeMap<String, Asset>,
    notes: &BTreeMap<String, String>,
    gated: &BTreeSet<String>,
) -> Result<Vec<reflow::article::Mount<'a>>, String> {
    list.iter()
        .map(|w| {
            let key = format!("{}-poster", w.id);
            let a = assets
                .get(&key)
                .ok_or_else(|| format!("widget {}: it has no poster asset", w.id))?;
            let poster = match (a.mode, &a.data) {
                (Mode::Bundled, _) => a.path(),
                (_, Bytes::File(p)) => data_url(&a.mime, &read_verified(p, &a.sha)?),
                (_, Bytes::Mem(b)) => data_url(&a.mime, b),
                _ => return Err(format!("widget {}: its poster has no bytes", w.id)),
            };
            let kind = match w.kind {
                WidgetType::Model => "model",
                WidgetType::Video => "video",
                WidgetType::Table => "table",
                WidgetType::Chart => "chart",
                WidgetType::Html => "html",
                WidgetType::Custom => "custom",
            };
            let size = (w.kind == WidgetType::Model)
                .then(|| {
                    w.options
                        .iter()
                        .find(|o| o.key == "size")
                        .map(|o| crate::widgets::params::size(&o.value))
                })
                .flatten()
                .transpose()
                .map_err(|e| format!("widget {}: {e}", w.id))?;
            let rect = (w.rect.x1 - w.rect.x0, w.rect.y1 - w.rect.y0);
            let author = (
                author_pt(&w.options, "width"),
                author_pt(&w.options, "height"),
            );
            let (frame, author_box) = reflow::article::frame(kind, size, author, rect);
            Ok(reflow::article::Mount {
                id: &w.id,
                kind,
                figure: w.figure.as_deref(),
                label: w.label.as_deref(),
                alt: &w.alt,
                width: frame.0,
                height: frame.1,
                author_width: author_box.map(|b| b.0),
                author_height: author_box.map(|b| b.1),
                poster,
                note: notes.get(&w.id).cloned(),
                approval_required: gated.contains(&w.id),
            })
        })
        .collect()
}

/// An author's `width=`/`height=` sidecar value in points: the package
/// canonicalizes dims through a length, so a well-formed one ends in `pt`.
/// Anything else is no dims, never a failure.
fn author_pt(options: &[crate::widgets::WidgetOption], key: &str) -> Option<f64> {
    options
        .iter()
        .find(|o| o.key == key)
        .and_then(|o| o.value.strip_suffix("pt"))
        .and_then(|n| n.parse::<f64>().ok())
        .filter(|v| v.is_finite() && *v > 0.0)
}

/// An app-owned scratch folder for one export's conversion and figures,
/// removed when the export ends either way.
struct Scratch(PathBuf);

impl Scratch {
    fn new(outdir: &Path) -> Result<Scratch, String> {
        static NEXT: std::sync::atomic::AtomicU64 = std::sync::atomic::AtomicU64::new(0);
        let n = NEXT.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
        let dir = outdir.join(format!("reader-export-{}-{n}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(dir.join("convert"))
            .map_err(|e| format!("cannot create {}: {e}", dir.display()))?;
        Ok(Scratch(dir))
    }
}

impl Drop for Scratch {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.0);
    }
}

/// At most this many log errors are quoted in the report.
const QUOTED_ERRORS: usize = 5;

/// Packages that only work with shell escape: the converter never enables
/// it, so a conversion that names one reports it as such. Mirrors the
/// compile's list (`structure/src/checks.rs` `SHELL_ESCAPE_PACKAGES`).
const SHELL_ESCAPE_PACKAGES: &[&str] = &[
    "minted",
    "pythontex",
    "svg",
    "gnuplottex",
    "auto-pst-pdf",
    "bashful",
    "shellesc",
];

/// Whether a missing bundle file is one of those shell-escape packages.
fn shell_escape_package(file: &str) -> Option<&str> {
    let base = file.rsplit('/').next().unwrap_or(file);
    let stem = base
        .strip_suffix(".sty")
        .or_else(|| base.strip_suffix(".cls"))?;
    SHELL_ESCAPE_PACKAGES.iter().find(|p| **p == stem).copied()
}

/// The report lines for what the article pipeline found.
fn article_warnings(
    log: &str,
    log_errors: &[String],
    issues: &[reflow::article::Issue],
) -> Vec<BundleWarning> {
    use reflow::article::Issue;
    let mut out = Vec::new();
    // The generic quote skips undefined-macro detail lines: each macro gets
    // its own warning below.
    let quoted: Vec<&String> = log_errors
        .iter()
        .filter(|l| !l.starts_with("Error:undefined:"))
        .collect();
    if !quoted.is_empty() {
        let shown = quoted
            .iter()
            .take(QUOTED_ERRORS)
            .map(|l| l.as_str())
            .collect::<Vec<_>>()
            .join("; ");
        let more = quoted.len().saturating_sub(QUOTED_ERRORS);
        out.push(BundleWarning {
            kind: BundleWarningKind::Conversion,
            message: format!(
                "the conversion to HTML reported {} error{}; the article was still produced: {shown}{}",
                quoted.len(),
                if quoted.len() == 1 { "" } else { "s" },
                if more > 0 { format!(" and {more} more") } else { String::new() }
            ),
        });
    }
    // One warning per undefined macro: the article's spots first, then any
    // macro the log named that left no mark in the article.
    let mut groups: BTreeMap<String, usize> = BTreeMap::new();
    for i in issues {
        if let Issue::Undefined(found) = i {
            for u in found {
                groups.insert(u.name.clone(), u.spots);
            }
        }
    }
    for u in reflow::convert::undefined_from_log(log) {
        groups.entry(u.name).or_insert(u.spots);
    }
    let mut groups: Vec<(String, usize)> = groups.into_iter().collect();
    groups.sort_by(|a, b| b.1.cmp(&a.1).then(a.0.cmp(&b.0)));
    for (name, spots) in groups {
        let where_ = if spots > 0 {
            format!(
                "{} spot{} in the article show{} raw TeX",
                spots,
                if spots == 1 { "" } else { "s" },
                if spots == 1 { "s" } else { "" }
            )
        } else {
            String::from("the converter reported it, but it left no mark in the article")
        };
        out.push(BundleWarning {
            kind: BundleWarningKind::Conversion,
            message: format!(
                "{name} is not defined ({where_}); the package is not in the TeX bundle: add it to your project folder next to your main file."
            ),
        });
    }
    // Files the log says the bundle lacks: shell-escape packages report as
    // such, the rest (too new for the pinned bundle, or never in TeX Live)
    // get the project-folder hint.
    let mut shell_reported: Vec<String> = Vec::new();
    for file in reflow::convert::missing_from_log(log) {
        if let Some(pkg) = shell_escape_package(&file) {
            if !shell_reported.contains(&pkg.to_string()) {
                shell_reported.push(pkg.to_string());
            }
        } else {
            out.push(BundleWarning {
                kind: BundleWarningKind::Conversion,
                message: super::compile::missing_package_text(&file),
            });
        }
    }
    for line in log.lines() {
        let lower = line.to_ascii_lowercase();
        if lower.contains("shell-escape")
            || lower.contains("shell escape")
            || lower.contains("write18")
        {
            // The compile's shape names the package (`Package minted
            // Error: ...`); otherwise any shell-escape package word on the
            // line does.
            let pkg = line
                .find("Package ")
                .and_then(|at| {
                    line[at + "Package ".len()..]
                        .split_whitespace()
                        .next()
                        .map(|w| w.trim_matches(|c: char| !c.is_alphanumeric() && c != '-'))
                })
                .filter(|w| !w.is_empty())
                .map(str::to_string)
                .or_else(|| {
                    line.split(|c: char| !c.is_alphanumeric() && c != '-' && c != '_')
                        .map(|w| w.trim_matches('-'))
                        .find(|w| SHELL_ESCAPE_PACKAGES.contains(w))
                        .map(str::to_string)
                });
            match pkg {
                Some(p) if !shell_reported.contains(&p) => shell_reported.push(p),
                None if !shell_reported.iter().any(|p| p.is_empty()) => {
                    shell_reported.push(String::new());
                }
                _ => {}
            }
        }
    }
    for pkg in shell_reported {
        out.push(BundleWarning {
            kind: BundleWarningKind::Conversion,
            message: if pkg.is_empty() {
                String::from(
                    "the conversion needs shell escape, which the converter never enables; the article was still produced.",
                )
            } else {
                format!(
                    "{pkg} needs shell escape, which the converter never enables; the article was still produced."
                )
            },
        });
    }
    for i in issues {
        out.push(match i {
            Issue::Undefined(_) => continue,
            Issue::Join(e) => BundleWarning {
                kind: BundleWarningKind::WidgetJoin,
                message: format!("the widgets could not be placed in the article ({e}); they are listed at its end"),
            },
            Issue::Figure(w) => BundleWarning {
                kind: BundleWarningKind::Figure,
                message: if w.file.is_empty() {
                    format!("a figure is not shown: {}", w.reason.describe())
                } else {
                    format!("figure {} is not shown: {}", w.file, w.reason.describe())
                },
            },
        });
    }
    out
}

fn data_url(mime: &str, bytes: &[u8]) -> String {
    format!(
        "data:{mime};base64,{}",
        base64::engine::general_purpose::STANDARD.encode(bytes)
    )
}

fn read_verified(path: &Path, sha: &str) -> Result<Vec<u8>, String> {
    let b = std::fs::read(path).map_err(|e| format!("cannot read {}: {e}", path.display()))?;
    if sha_of(&b) != sha {
        return Err(format!(
            "{} changed while it was being exported: run the export again",
            path.display()
        ));
    }
    Ok(b)
}

fn put(root: &Path, rel: &str, bytes: &[u8], total: &mut u64) -> Result<(), String> {
    let p = root.join(rel);
    if let Some(parent) = p.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|e| format!("cannot create {}: {e}", parent.display()))?;
    }
    std::fs::File::create(&p)
        .and_then(|mut f| f.write_all(bytes))
        .map_err(|e| format!("cannot write {}: {e}", p.display()))?;
    *total += bytes.len() as u64;
    Ok(())
}

/// Whether `dir` holds an earlier bundle of ours (its manifest names the
/// format): the only non-empty folder an export replaces.
fn is_earlier_bundle(dir: &Path) -> bool {
    std::fs::read_to_string(dir.join("manifest.json"))
        .ok()
        .and_then(|t| serde_json::from_str::<Value>(&t).ok())
        .is_some_and(|v| v["format"] == FORMAT)
}

/// What an export may do at `dest` before anything is written.
fn check_destination(root: &Path, dest: &str, profile: BundleProfile) -> Result<PathBuf, String> {
    let out = crate::export::destination(root, dest)?;
    if root.starts_with(&out) {
        return Err(
            "export destination contains the project: choose a folder outside it".to_string(),
        );
    }
    match std::fs::symlink_metadata(&out) {
        Err(_) => {}
        Ok(m) if m.file_type().is_symlink() => {
            return Err(format!(
                "export destination is a symlink: {}",
                out.display()
            ));
        }
        Ok(m) => match profile {
            BundleProfile::SingleFile => {
                if m.is_dir() {
                    return Err(format!("export destination is a folder: {}", out.display()));
                }
            }
            _ => {
                if !m.is_dir() {
                    return Err(format!("export destination is a file: {}", out.display()));
                }
                let empty = std::fs::read_dir(&out)
                    .map_err(|e| format!("cannot list {}: {e}", out.display()))?
                    .next()
                    .is_none();
                if !empty && !is_earlier_bundle(&out) {
                    return Err(format!(
                        "export destination is not empty and is not an earlier bundle: {}",
                        out.display()
                    ));
                }
            }
        },
    }
    Ok(out)
}

fn staging_name(out: &Path) -> PathBuf {
    let name = out
        .file_name()
        .map(|n| n.to_string_lossy().to_string())
        .unwrap_or_default();
    out.with_file_name(format!(".{name}.mfw-partial-{}", std::process::id()))
}

/// Exports a paper bundle with no network and no approvals: the call the
/// automation surface makes.
pub fn export_bundle(
    cx: &Core,
    root_id: &str,
    main_rel: &str,
    dest: &str,
    profile: BundleProfile,
    size_cap_bytes: Option<u64>,
) -> Result<BundleExported, String> {
    export_bundle_with(
        cx,
        root_id,
        main_rel,
        dest,
        profile,
        &BundleOptions {
            size_cap_bytes,
            ..BundleOptions::default()
        },
    )
}

/// The browser preview: the single-file bundle of `main_rel`'s last compile,
/// written as `index.html` into a scratch folder under the OS app-data dir
/// (never in the project). One folder per project, replaced on the next run,
/// so only the latest preview is kept. The caller decides whether to open it.
pub fn preview_bundle(cx: &Core, root_id: &str, main_rel: &str) -> Result<BundleExported, String> {
    preview_bundle_in(
        cx,
        root_id,
        main_rel,
        &crate::data_base_dir().join("bundle-previews"),
    )
}

/// `preview_bundle` with the scratch base chosen by the caller.
pub(crate) fn preview_bundle_in(
    cx: &Core,
    root_id: &str,
    main_rel: &str,
    base: &Path,
) -> Result<BundleExported, String> {
    let root = crate::fs::session_root(cx, root_id)?;
    let dir = preview_dir(base, &root);
    if dir.starts_with(&root) || root.starts_with(&dir) {
        return Err(format!(
            "the preview folder {} overlaps the project: refusing to write there",
            dir.display()
        ));
    }
    // Clean the previous preview first, so a failed export leaves nothing stale.
    if dir.exists() {
        std::fs::remove_dir_all(&dir)
            .map_err(|e| format!("cannot clear the old preview {}: {e}", dir.display()))?;
    }
    std::fs::create_dir_all(&dir)
        .map_err(|e| format!("cannot create the preview folder {}: {e}", dir.display()))?;
    let dest = dir.join("index.html");
    // The preview runs custom runtimes unjudged, as it runs html widgets:
    // the approval gate applies to exports only.
    let r = export_inner(
        cx,
        root_id,
        main_rel,
        &dest.to_string_lossy(),
        BundleProfile::SingleFile,
        &BundleOptions::default(),
        Gate::Preview,
    );
    if r.is_err() {
        let _ = std::fs::remove_dir_all(&dir);
    }
    r
}

/// The in-app article: the single-file bundle of `main_rel`'s last compile,
/// written as `index.html` into a scratch folder under the OS app-data dir
/// (never in the project, beside the browser previews but separate from
/// them). One folder per project, replaced on the next run. Unlike the
/// browser preview, the approval gate applies: custom runtimes are judged
/// and unapproved html widgets are held back to their posters.
pub fn article_bundle(cx: &Core, root_id: &str, main_rel: &str) -> Result<ArticleView, String> {
    article_bundle_in(
        cx,
        root_id,
        main_rel,
        &crate::data_base_dir().join("article-previews"),
        &crate::widget_approval::store_base(),
    )
}

/// `article_bundle` with the scratch base and the approval store chosen by
/// the caller.
pub(crate) fn article_bundle_in(
    cx: &Core,
    root_id: &str,
    main_rel: &str,
    base: &Path,
    approvals: &Path,
) -> Result<ArticleView, String> {
    let root = crate::fs::session_root(cx, root_id)?;
    let dir = preview_dir(base, &root);
    if dir.starts_with(&root) || root.starts_with(&dir) {
        return Err(format!(
            "the article folder {} overlaps the project: refusing to write there",
            dir.display()
        ));
    }
    // Clean the previous article first, so a failed run leaves nothing stale.
    if dir.exists() {
        std::fs::remove_dir_all(&dir)
            .map_err(|e| format!("cannot clear the old article {}: {e}", dir.display()))?;
    }
    std::fs::create_dir_all(&dir)
        .map_err(|e| format!("cannot create the article folder {}: {e}", dir.display()))?;
    let dest = dir.join("index.html");
    let r = export_inner(
        cx,
        root_id,
        main_rel,
        &dest.to_string_lossy(),
        BundleProfile::SingleFile,
        &BundleOptions::default(),
        Gate::Article(approvals),
    );
    if r.is_err() {
        let _ = std::fs::remove_dir_all(&dir);
        r?;
        unreachable!("a failed article run returns above");
    }
    let html = std::fs::read_to_string(&dest)
        .map_err(|e| format!("cannot read the article {}: {e}", dest.display()))?;
    let anchors = reflow::article::anchors_of(&html)
        .into_iter()
        .map(|a| ArticleAnchor {
            id: a.id,
            text: a.text,
        })
        .collect();
    Ok(ArticleView { html, anchors })
}

/// `<base>/<first 16 hex of sha256(project root)>`: stable per project.
fn preview_dir(base: &Path, root: &Path) -> PathBuf {
    let digest = Sha256::digest(root.to_string_lossy().as_bytes());
    base.join(
        digest
            .iter()
            .take(8)
            .map(|b| format!("{b:02x}"))
            .collect::<String>(),
    )
}

/// Exports a paper bundle of `main_rel`'s last compile to `dest`, outside the
/// project. Custom runtimes are judged against the app's approvals.
pub fn export_bundle_with(
    cx: &Core,
    root_id: &str,
    main_rel: &str,
    dest: &str,
    profile: BundleProfile,
    opts: &BundleOptions,
) -> Result<BundleExported, String> {
    let base = crate::widget_approval::store_base();
    export_inner(
        cx,
        root_id,
        main_rel,
        dest,
        profile,
        opts,
        Gate::Approvals(&base),
    )
}

/// [`export_bundle`] judging custom runtimes against the approval store at
/// `base` (tests stand in for app data).
#[cfg(test)]
pub(crate) fn export_bundle_at(
    base: &Path,
    cx: &Core,
    root_id: &str,
    main_rel: &str,
    dest: &str,
    profile: BundleProfile,
) -> Result<BundleExported, String> {
    export_inner(
        cx,
        root_id,
        main_rel,
        dest,
        profile,
        &BundleOptions::default(),
        Gate::Approvals(base),
    )
}

fn export_inner(
    cx: &Core,
    root_id: &str,
    main_rel: &str,
    dest: &str,
    profile: BundleProfile,
    opts: &BundleOptions,
    gate: Gate,
) -> Result<BundleExported, String> {
    let root = crate::fs::session_root(cx, root_id)?;
    let out = check_destination(&root, dest, profile)?;

    // The typed widget list is the join of sidecar and pdf; it also fails when
    // the main file was never compiled.
    let (list, theme) = crate::widgets::read(cx, root_id, main_rel)?;
    // The page's CSS and the widgets' tokens come from this one theme;
    // its values are checked again as the CSS is written.
    let mut theme_css = theme.css()?;
    let o = crate::outputs::outputs_of(cx, root_id, main_rel)?;
    let pdf_bytes = std::fs::read(o.outdir.join(&o.pdf_name))
        .map_err(|_| format!("{main_rel} has no compiled pdf: compile it first"))?;
    let pdf = hayro::hayro_syntax::Pdf::new(pdf_bytes.clone())
        .map_err(|e| format!("cannot read the pdf of {main_rel}: {e:?}"))?;
    let pages = pdf.pages().len() as u32;
    if pages == 0 || pdf_bytes.is_empty() {
        return Err(format!("the pdf of {main_rel} has no pages"));
    }

    let mut theme_ids: BTreeSet<&str> = list.widgets.iter().map(|w| w.theme.as_str()).collect();
    if theme_ids.is_empty() {
        theme_ids.insert("house");
    }
    if theme_ids.len() > 1 {
        return Err(format!(
            "the widgets name more than one theme ({}): the paper has one",
            theme_ids.iter().copied().collect::<Vec<_>>().join(", ")
        ));
    }
    let theme_id = theme_ids.into_iter().next().unwrap_or("house").to_string();
    if theme_id != "house" {
        return Err(format!(
            "theme `{theme_id}` is not available: only the built-in house theme is in this build"
        ));
    }

    let mut plan = Plan {
        cx,
        root_id,
        main_rel,
        root: root.clone(),
        main_dir_rel: Path::new(main_rel)
            .parent()
            .map(Path::to_path_buf)
            .unwrap_or_default(),
        profile,
        opts,
        theme: &theme,
        assets: BTreeMap::new(),
        warnings: Vec::new(),
        gate,
        users: BTreeMap::new(),
        runtimes: BTreeMap::new(),
        runtime_entries: Map::new(),
        fallbacks: BTreeMap::new(),
        wasm_live: false,
        notes: BTreeMap::new(),
        gated: BTreeSet::new(),
    };
    for w in list.widgets.iter().filter(|w| w.kind == WidgetType::Custom) {
        if let Some(r) = &w.runtime {
            plan.users.entry(r.clone()).or_default().push(w.id.clone());
        }
    }
    // The author's reader stylesheet follows the theme's tokens, so it can
    // restyle with them; refused, the page keeps the theme alone.
    if let Some(style) = &theme.style {
        match crate::reader_style::load(cx, root_id, &plan.main_dir_rel, style) {
            Ok(css) => {
                theme_css.push('\n');
                theme_css.push_str(&css);
            }
            Err(e) => plan.warn(BundleWarningKind::ReaderStyle, e),
        }
    }

    let stem = o
        .main_file
        .strip_suffix(".tex")
        .unwrap_or(&o.main_file)
        .to_string();
    let tex = std::fs::read_to_string(root.join(&plan.main_dir_rel).join(&o.main_file))
        .map_err(|e| format!("cannot read {main_rel}: {e}"))?;
    let meta = paper_meta(&tex, &stem, &mut plan.warnings);

    let mut planned = Vec::new();
    for w in &list.widgets {
        planned.push(plan_widget(&mut plan, w, &pdf, pages)?);
    }
    for (r, (why, ids)) in std::mem::take(&mut plan.fallbacks) {
        plan.warn(BundleWarningKind::Runtime, why.warning(&r, &ids.join(", ")));
    }
    let single = profile == BundleProfile::SingleFile;

    // The article: the main file converted to HTML, then the reader pipeline
    // (figures, widget mounts, contents, sanitizing). Its problems are
    // reported; only a conversion that produced no HTML at all refuses.
    let scratch = Scratch::new(&o.outdir)?;
    let main_canon = crate::fs::resolve_in(cx, root_id, main_rel)?;
    let main_dir = main_canon
        .parent()
        .map(Path::to_path_buf)
        .ok_or_else(|| format!("{main_rel} has no folder"))?;
    let conversion =
        reflow::convert::converter(cx).convert(cx, &main_canon, &scratch.0.join("convert"));
    let converted = conversion.html.map_err(|e| {
        format!("{main_rel} could not be converted to HTML, so the bundle has no article: {e}")
    })?;
    // Reader flags: the marker classes the `\maleficiumcontents` and
    // `\maleficiummeasure` calls left in the conversion, resolved where the
    // widgets are joined and stripped from the article.
    let flag_scan = flags::scan(&converted);
    for w in &flag_scan.warnings {
        plan.warn(BundleWarningKind::Conversion, w.clone());
    }
    let converted = flag_scan.html;
    let sidecar = std::fs::read_to_string(o.outdir.join(format!("{stem}.mfw"))).ok();
    let mount_units = mounts(&list.widgets, &plan.assets, &plan.notes, &plan.gated)?;
    let article = reflow::article::build(reflow::article::Input {
        html: &converted,
        root: &main_dir,
        mode: if single {
            reflow::figures::Mode::SingleFile
        } else {
            reflow::figures::Mode::Folder {
                dir: scratch.0.clone(),
            }
        },
        graphics_paths: graphics_paths(&tex),
        sidecar: sidecar.as_deref(),
        mounts: &mount_units,
        title: &meta.title,
    })?;
    plan.warnings.extend(article_warnings(
        &conversion.log,
        &conversion.errors,
        &article.issues,
    ));
    // `contents: false` omits the nav (not-emit), rather than hiding it.
    let article_html = if flag_scan.flags.contents {
        article.html
    } else {
        flags::omit_contents(&article.html)
    };

    let mut paper = Map::new();
    paper.insert("title".into(), meta.title.clone().into());
    paper.insert(
        "authors".into(),
        Value::Array(
            meta.authors
                .iter()
                .map(|(n, aff)| {
                    let mut a = Map::new();
                    a.insert("name".into(), n.clone().into());
                    if !aff.is_empty() {
                        a.insert("affiliations".into(), json!(aff));
                    }
                    Value::Object(a)
                })
                .collect(),
        ),
    );
    if let Some(a) = &meta.abstract_text {
        paper.insert("abstract".into(), a.clone().into());
    }
    paper.insert(
        "reader".into(),
        json!({
            "contents": flag_scan.flags.contents,
            "measure": flag_scan.flags.measure.token(),
        }),
    );
    let cap = opts.size_cap_bytes.unwrap_or(DEFAULT_SIZE_CAP_BYTES);
    let mut manifest = Map::new();
    manifest.insert("format".into(), FORMAT.into());
    manifest.insert("formatVersion".into(), 1.into());
    manifest.insert(
        "generator".into(),
        json!({ "name": "maleficium", "version": env!("CARGO_PKG_VERSION") }),
    );
    manifest.insert(
        "profile".into(),
        serde_json::to_value(profile).map_err(|e| e.to_string())?,
    );
    if single {
        manifest.insert("sizeCapBytes".into(), cap.into());
    }
    manifest.insert("paper".into(), Value::Object(paper));
    manifest.insert(
        "pdf".into(),
        json!({
            "path": if single { Value::Null } else { "paper.pdf".into() },
            "sha256": sha_of(&pdf_bytes),
            "bytes": pdf_bytes.len(),
            "pages": pages
        }),
    );
    manifest.insert(
        "theme".into(),
        json!({ "id": theme_id, "contractVersion": CONTRACT_VERSION }),
    );
    manifest.insert(
        "widgets".into(),
        Value::Array(planned.iter().map(|p| p.json.clone()).collect()),
    );
    if !plan.runtime_entries.is_empty() {
        manifest.insert(
            "runtimes".into(),
            Value::Object(std::mem::take(&mut plan.runtime_entries)),
        );
    }
    manifest.insert(
        "assets".into(),
        Value::Object(
            plan.assets
                .iter()
                .map(|(k, a)| (k.clone(), a.record()))
                .collect(),
        ),
    );
    let manifest = Value::Object(manifest);
    validate_manifest(&manifest)?;

    // Writing starts only now: every read, hash and check above has passed.
    let stage = staging_name(&out);
    let _ = std::fs::remove_dir_all(&stage);
    let _ = std::fs::remove_file(&stage);
    let mut total = 0u64;
    let manifest_text = serde_json::to_string_pretty(&manifest).map_err(|e| e.to_string())? + "\n";

    // Every frame origin some widget declared: the reader's own frame-src.
    let frames: Vec<String> = planned
        .iter()
        .flat_map(|p| p.frames.iter().cloned())
        .collect::<BTreeSet<_>>()
        .into_iter()
        .collect();
    let written = (|| -> Result<(), String> {
        if single {
            let mut assets = Map::new();
            for a in plan.assets.values().filter(|a| a.mode == Mode::Inline) {
                if assets.contains_key(&a.sha) {
                    continue;
                }
                let bytes = match &a.data {
                    Bytes::File(p) => read_verified(p, &a.sha)?,
                    Bytes::Mem(b) => b.clone(),
                    Bytes::None => continue,
                };
                assets.insert(
                    a.sha.clone(),
                    base64::engine::general_purpose::STANDARD
                        .encode(bytes)
                        .into(),
                );
            }
            let widgets: Map<String, Value> = planned
                .iter()
                .filter_map(|p| p.doc.clone().map(|d| (p.id.clone(), d.into())))
                .collect();
            let islands = [
                island("mfw-manifest", &manifest),
                island("mfw-widgets", &Value::Object(widgets)),
                island("mfw-assets", &Value::Object(assets)),
            ]
            .concat();
            let html = reader::render(&reader::Reader {
                title: &meta.title,
                folder: false,
                article: &article_html,
                measure: flag_scan.flags.measure,
                pdf: Some(&pdf_bytes),
                islands: &islands,
                frames: &frames,
                wasm: plan.wasm_live,
                theme: &theme,
                theme_css: &theme_css,
            });
            std::fs::write(&stage, html.as_bytes())
                .map_err(|e| format!("cannot write {}: {e}", stage.display()))?;
            total = html.len() as u64;
        } else {
            std::fs::create_dir_all(&stage)
                .map_err(|e| format!("cannot create {}: {e}", stage.display()))?;
            put(
                &stage,
                "manifest.json",
                manifest_text.as_bytes(),
                &mut total,
            )?;
            put(&stage, "paper.pdf", &pdf_bytes, &mut total)?;
            put(
                &stage,
                "theme/theme.json",
                theme_json(&theme_id).as_bytes(),
                &mut total,
            )?;
            put(&stage, "theme/theme.css", theme_css.as_bytes(), &mut total)?;
            for p in &planned {
                if let Some(doc) = &p.doc {
                    put(
                        &stage,
                        &format!("widgets/{}/index.html", p.id),
                        doc.as_bytes(),
                        &mut total,
                    )?;
                }
            }
            let mut inline = Map::new();
            let mut stored = BTreeSet::new();
            for a in plan.assets.values() {
                let bytes = match (&a.data, a.mode) {
                    (_, Mode::Remote) | (Bytes::None, _) => continue,
                    (Bytes::File(p), _) => read_verified(p, &a.sha)?,
                    (Bytes::Mem(b), _) => b.clone(),
                };
                if a.mode == Mode::Inline {
                    inline.insert(
                        a.sha.clone(),
                        base64::engine::general_purpose::STANDARD
                            .encode(&bytes)
                            .into(),
                    );
                } else if stored.insert(a.path()) {
                    put(&stage, &a.path(), &bytes, &mut total)?;
                }
            }
            let islands = [
                island("mfw-manifest", &manifest),
                if inline.is_empty() {
                    String::new()
                } else {
                    island("mfw-assets", &Value::Object(inline))
                },
            ]
            .concat();
            // The figures the article references, written by the pipeline
            // into the scratch folder (content-addressed names).
            let figures = scratch.0.join("figures");
            if figures.is_dir() {
                let entries = std::fs::read_dir(&figures)
                    .map_err(|e| format!("cannot list {}: {e}", figures.display()))?;
                for e in entries.flatten() {
                    let name = e.file_name().to_string_lossy().to_string();
                    if name.ends_with(".part") {
                        continue;
                    }
                    let bytes = std::fs::read(e.path())
                        .map_err(|err| format!("cannot read {}: {err}", e.path().display()))?;
                    put(&stage, &format!("figures/{name}"), &bytes, &mut total)?;
                }
            }
            let html = reader::render(&reader::Reader {
                title: &meta.title,
                folder: true,
                article: &article_html,
                measure: flag_scan.flags.measure,
                pdf: None,
                islands: &islands,
                frames: &frames,
                wasm: plan.wasm_live,
                theme: &theme,
                theme_css: &theme_css,
            });
            put(&stage, "index.html", html.as_bytes(), &mut total)?;
        }
        Ok(())
    })();
    if let Err(e) = written {
        let _ = std::fs::remove_dir_all(&stage);
        let _ = std::fs::remove_file(&stage);
        return Err(e);
    }

    if single && total > cap {
        plan.warn(
            BundleWarningKind::SizeCap,
            format!(
                "the single-file bundle is {total} bytes, over the {cap} byte cap; it was written anyway"
            ),
        );
    }

    let moved = (|| -> Result<(), String> {
        match std::fs::symlink_metadata(&out) {
            Ok(m) if m.is_dir() => {
                std::fs::remove_dir_all(&out)
                    .map_err(|e| format!("cannot replace {}: {e}", out.display()))?;
            }
            Ok(_) => {
                std::fs::remove_file(&out)
                    .map_err(|e| format!("cannot replace {}: {e}", out.display()))?;
            }
            Err(_) => {}
        }
        std::fs::rename(&stage, &out)
            .map_err(|e| format!("cannot place the bundle at {}: {e}", out.display()))
    })();
    if let Err(e) = moved {
        let _ = std::fs::remove_dir_all(&stage);
        let _ = std::fs::remove_file(&stage);
        return Err(e);
    }

    Ok(BundleExported {
        path: out.to_string_lossy().to_string(),
        profile,
        bytes: total,
        widgets: planned.len() as u32,
        assets: plan.assets.len() as u32,
        warnings: plan.warnings,
    })
}

/// The bus event for one export call, shared by the adapters that log it.
pub fn event(
    main_rel: &str,
    profile: BundleProfile,
    r: &Result<BundleExported, String>,
    actor: maleficium_events::Actor,
) -> maleficium_events::BusEvent {
    use maleficium_events::{AppEvent, BusEvent, EventKind, EventScope};
    let (kind, message, event) = match r {
        Ok(b) => (
            if b.warnings.is_empty() {
                EventKind::Success
            } else {
                EventKind::Warn
            },
            format!(
                "exported a {} bundle of {main_rel} to {}",
                profile_name(profile),
                b.path
            ),
            AppEvent::BundleExported {
                main: main_rel.to_string(),
                profile,
                path: b.path.clone(),
                bytes: b.bytes,
                widgets: b.widgets,
                warnings: b.warnings.len() as u32,
            },
        ),
        Err(e) => (
            EventKind::Error,
            format!("bundle export of {main_rel} refused"),
            AppEvent::BundleFailed {
                main: main_rel.to_string(),
                profile,
                error: e.chars().take(300).collect(),
            },
        ),
    };
    BusEvent {
        at: crate::eventlog::now_ms(),
        scope: EventScope::App,
        kind,
        actor,
        message,
        event,
    }
}

fn profile_name(p: BundleProfile) -> &'static str {
    match p {
        BundleProfile::Folder => "folder",
        BundleProfile::SingleFile => "single-file",
        BundleProfile::Hosted => "hosted",
    }
}

#[cfg(test)]
mod tests;
