//! Paper bundle export: a compiled main file, its widgets and its assets
//! written as the layout of `notes/interactive-papers/2026-09-25-bundle-spec.md`
//! to a destination outside the project root.
//!
//! The export reads project files and the compiled output; it never fetches.
//! A remote asset with no local copy would need a download to be hashed, and
//! that download is refused unless the user approved that exact url for this
//! export. The approval is an argument of [`export_bundle_with`] that only
//! the app's own user action can set; the automation surface calls
//! [`export_bundle`], which takes none.
//!
//! Everything is read, hashed and checked before anything is written, and the
//! bundle is assembled in a sibling staging folder and moved into place, so a
//! refusal or a failure leaves no half-written destination.
//!
//! Widgets are folded into one inline document each in every profile (the
//! 2026-09-30 browser export spike): see [`fold`].

pub(crate) mod fold;

use crate::widgets::{Widget, WidgetRect, WidgetSource, WidgetType};
use crate::Core;

pub use maleficium_events::BundleProfile;

use base64::Engine;
use serde::{Deserialize, Serialize};
use serde_json::{json, Map, Value};
use sha2::{Digest, Sha256};
use std::collections::{BTreeMap, BTreeSet};
use std::io::{Read, Write};
use std::path::{Path, PathBuf};
use ts_rs::TS;

/// The committed manifest schema (JSON Schema 2020-12); the bundle spec
/// points here.
pub const MANIFEST_SCHEMA: &str = include_str!("../schemas/paper-bundle-1.schema.json");

/// The single-file profile warns above this many bytes unless the caller
/// configures another cap.
pub const DEFAULT_SIZE_CAP_BYTES: u64 = 50 * 1024 * 1024;

const FORMAT: &str = "maleficium-paper-bundle";
const CONTRACT_VERSION: u32 = 1;
/// Built-in runtime hosts, generated by `npm run build:runtimes`.
const TABLE_HOST: &str = include_str!("../../widget-runtimes/table/index.html");
const CHART_HOST: &str = include_str!("../../widget-runtimes/chart/index.html");

/// Downloads one url for an approved export. Core has no implementation: the
/// app does not fetch on its own.
pub trait Fetcher {
    fn fetch(&self, url: &str) -> Result<Vec<u8>, String>;
}

/// What one export is allowed to do beyond reading the project.
#[derive(Default)]
pub struct BundleOptions<'a> {
    /// Single-file warning threshold; [`DEFAULT_SIZE_CAP_BYTES`] when absent.
    pub size_cap_bytes: Option<u64>,
    /// Urls the user approved fetching, for this export only.
    pub approved_fetch: &'a [String],
    /// Who fetches an approved url.
    pub fetcher: Option<&'a dyn Fetcher>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, schemars::JsonSchema, TS)]
#[serde(rename_all = "kebab-case")]
pub enum BundleWarningKind {
    /// The single-file output is larger than its cap.
    SizeCap,
    /// A widget's built-in runtime is not in this build: it exports as its
    /// poster.
    NoRuntime,
    /// Files of an author bundle that nothing inlined and so cannot load.
    UnfoldedFiles,
    /// An author bundle references another origin.
    ExternalReference,
    /// Another folding limit (module imports, css `@import`, oversized file).
    FoldLimit,
    /// Paper metadata the export could not read from the source.
    Metadata,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, schemars::JsonSchema, TS)]
pub struct BundleWarning {
    pub kind: BundleWarningKind,
    pub message: String,
}

/// What an export wrote.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, schemars::JsonSchema, TS)]
#[serde(rename_all = "camelCase")]
pub struct BundleExported {
    /// The folder (folder, hosted) or the file (single-file) written.
    pub path: String,
    pub profile: BundleProfile,
    /// Total bytes written.
    pub bytes: u64,
    pub widgets: u32,
    pub assets: u32,
    pub warnings: Vec<BundleWarning>,
}

#[derive(Clone, Copy, PartialEq, Eq)]
enum Mode {
    Bundled,
    Inline,
    Remote,
}

impl Mode {
    fn name(self) -> &'static str {
        match self {
            Mode::Bundled => "bundled",
            Mode::Inline => "inline",
            Mode::Remote => "remote",
        }
    }
}

/// Where an asset's bytes come from at write time.
enum Bytes {
    File(PathBuf),
    Mem(Vec<u8>),
    /// A remote asset: nothing is stored.
    None,
}

struct Asset {
    mode: Mode,
    sha: String,
    bytes: u64,
    mime: String,
    ext: String,
    source: Option<String>,
    url: Option<String>,
    data: Bytes,
}

impl Asset {
    fn path(&self) -> String {
        format!("assets/{}.{}", self.sha, self.ext)
    }

    fn record(&self) -> Value {
        let mut o = Map::new();
        o.insert("mode".into(), self.mode.name().into());
        match self.mode {
            Mode::Bundled => {
                o.insert("path".into(), self.path().into());
            }
            Mode::Inline => {
                o.insert("path".into(), Value::Null);
            }
            Mode::Remote => {
                o.insert("url".into(), self.url.clone().into());
            }
        }
        o.insert("sha256".into(), self.sha.clone().into());
        o.insert("bytes".into(), self.bytes.into());
        o.insert("mime".into(), self.mime.clone().into());
        if let Some(s) = &self.source {
            o.insert("source".into(), s.clone().into());
        }
        Value::Object(o)
    }
}

/// One widget as the manifest records it, and its folded document.
struct Planned {
    json: Value,
    id: String,
    doc: String,
}

fn hex(bytes: &[u8]) -> String {
    use std::fmt::Write as _;
    bytes.iter().fold(String::new(), |mut s, b| {
        let _ = write!(s, "{b:02x}");
        s
    })
}

pub(crate) fn sha_of(bytes: &[u8]) -> String {
    hex(&Sha256::digest(bytes))
}

/// Streams a file through sha256: its digest and length.
fn hash_file(path: &Path) -> Result<(String, u64), String> {
    let mut f =
        std::fs::File::open(path).map_err(|e| format!("cannot read {}: {e}", path.display()))?;
    let mut h = Sha256::new();
    let mut buf = vec![0u8; 1 << 20];
    let mut n_total = 0u64;
    loop {
        let n = f
            .read(&mut buf)
            .map_err(|e| format!("cannot read {}: {e}", path.display()))?;
        if n == 0 {
            break;
        }
        h.update(&buf[..n]);
        n_total += n as u64;
    }
    Ok((hex(&h.finalize()), n_total))
}

/// A file extension safe for the `assets/<sha256>.<ext>` pattern.
fn safe_ext(path: &str) -> String {
    let ext: String = Path::new(path)
        .extension()
        .and_then(|e| e.to_str())
        .unwrap_or("")
        .to_ascii_lowercase()
        .chars()
        .filter(char::is_ascii_alphanumeric)
        .collect();
    if ext.is_empty() {
        "bin".to_string()
    } else {
        ext
    }
}

fn truthy(v: &str) -> bool {
    matches!(v.trim().to_ascii_lowercase().as_str(), "true" | "1" | "yes")
}

fn option<'a>(w: &'a Widget, key: &str) -> Option<&'a str> {
    w.options
        .iter()
        .find(|o| o.key == key)
        .map(|o| o.value.as_str())
}

// ---- paper metadata -----------------------------------------------------

/// The text of the brace group that starts at `s[i]` (a `{`), and the index
/// after its closing brace.
fn brace_group(s: &str, i: usize) -> Option<(String, usize)> {
    let b = s.as_bytes();
    if b.get(i) != Some(&b'{') {
        return None;
    }
    let mut depth = 0usize;
    let mut j = i;
    while j < b.len() {
        match b[j] {
            b'\\' => j += 1,
            b'{' => depth += 1,
            b'}' => {
                depth -= 1;
                if depth == 0 {
                    return Some((s[i + 1..j].to_string(), j + 1));
                }
            }
            _ => {}
        }
        j += 1;
    }
    None
}

fn strip_comments(tex: &str) -> String {
    tex.lines()
        .map(|l| {
            let b = l.as_bytes();
            let mut i = 0;
            while i < b.len() {
                if b[i] == b'\\' {
                    i += 2;
                    continue;
                }
                if b[i] == b'%' {
                    return &l[..i];
                }
                i += 1;
            }
            l
        })
        .collect::<Vec<_>>()
        .join("\n")
}

/// The first `\name{...}` (with an optional `[..]`) in `tex`.
fn command_arg(tex: &str, name: &str) -> Option<String> {
    let needle = format!("\\{name}");
    let mut from = 0;
    while let Some(p) = tex[from..].find(&needle) {
        let mut i = from + p + needle.len();
        from = i;
        let next = tex[i..].chars().next();
        if next.is_some_and(|c| c.is_ascii_alphabetic()) {
            continue;
        }
        let rest = tex[i..].trim_start();
        i = tex.len() - rest.len();
        let mut j = i;
        if tex[j..].starts_with('[') {
            match tex[j..].find(']') {
                Some(e) => j += e + 1,
                None => continue,
            }
            j = tex.len() - tex[j..].trim_start().len();
        }
        if let Some((g, _)) = brace_group(tex, j) {
            return Some(g);
        }
    }
    None
}

/// Plain text of a small LaTeX fragment: footnote-like groups dropped, `\\`
/// and `~` as spaces, other commands reduced to their argument.
fn plain(s: &str) -> String {
    let mut s = s.to_string();
    for drop in ["thanks", "footnote", "label"] {
        let needle = format!("\\{drop}");
        while let Some(p) = s.find(&needle) {
            let rest = &s[p + needle.len()..];
            let off = rest.len() - rest.trim_start().len();
            match brace_group(&s, p + needle.len() + off) {
                Some((_, end)) => s.replace_range(p..end, ""),
                None => s.replace_range(p..p + needle.len(), ""),
            }
        }
    }
    let s = s.replace("\\\\", " ").replace("\\&", "&").replace('~', " ");
    let cmd = regex::Regex::new(r"\\[A-Za-z]+\*?").unwrap();
    let s = cmd.replace_all(&s, "");
    let s: String = s.chars().filter(|c| *c != '{' && *c != '}').collect();
    s.split_whitespace().collect::<Vec<_>>().join(" ")
}

struct Meta {
    title: String,
    authors: Vec<(String, Vec<String>)>,
    abstract_text: Option<String>,
}

/// Title, authors and abstract of the main file, as far as its own preamble
/// and body say. Anything unreadable gets a named default and a warning.
fn paper_meta(tex: &str, stem: &str, warnings: &mut Vec<BundleWarning>) -> Meta {
    let tex = strip_comments(tex);
    let mut warn = |m: String| {
        warnings.push(BundleWarning {
            kind: BundleWarningKind::Metadata,
            message: m,
        })
    };
    let title = command_arg(&tex, "title")
        .map(|t| plain(&t))
        .filter(|t| !t.is_empty());
    let title = title.unwrap_or_else(|| {
        warn(format!(
            "the main file has no \\title: the manifest title is the file name `{stem}`"
        ));
        stem.to_string()
    });
    let mut authors: Vec<(String, Vec<String>)> = Vec::new();
    if let Some(a) = command_arg(&tex, "author") {
        let split = regex::Regex::new(r"\\(?:and|And|AND)\b").unwrap();
        for part in split.split(&a) {
            let lines: Vec<String> = part
                .split("\\\\")
                .map(plain)
                .filter(|l| !l.is_empty())
                .collect();
            if let Some((name, aff)) = lines.split_first() {
                authors.push((name.clone(), aff.to_vec()));
            }
        }
    }
    if authors.is_empty() {
        warn(
            "the main file has no \\author: the manifest lists one author with an empty name"
                .to_string(),
        );
        authors.push((String::new(), Vec::new()));
    }
    let abstract_text = tex
        .find("\\begin{abstract}")
        .and_then(|s| {
            let body = &tex[s + "\\begin{abstract}".len()..];
            body.find("\\end{abstract}").map(|e| plain(&body[..e]))
        })
        .filter(|a| !a.is_empty());
    Meta {
        title,
        authors,
        abstract_text,
    }
}

// ---- the planner --------------------------------------------------------

struct Plan<'a> {
    cx: &'a Core,
    root_id: &'a str,
    root: PathBuf,
    main_dir_rel: PathBuf,
    profile: BundleProfile,
    opts: &'a BundleOptions<'a>,
    assets: BTreeMap<String, Asset>,
    warnings: Vec<BundleWarning>,
}

impl Plan<'_> {
    fn warn(&mut self, kind: BundleWarningKind, message: String) {
        self.warnings.push(BundleWarning { kind, message });
    }

    /// A project file named relative to the main file's folder: resolved
    /// inside the root (symlinks that escape are refused) and a regular file.
    fn local(&self, widget: &str, rel: &str) -> Result<(PathBuf, String), String> {
        let joined = self.main_dir_rel.join(rel);
        let canon = crate::fs::resolve_in(self.cx, self.root_id, &joined.to_string_lossy())
            .map_err(|e| format!("widget {widget}: {rel}: {e}"))?;
        if !canon.is_file() {
            return Err(format!("widget {widget}: {rel} is not a file"));
        }
        let source = canon
            .strip_prefix(&self.root)
            .map_err(|_| format!("widget {widget}: {rel} is outside the project"))?
            .to_string_lossy()
            .replace('\\', "/");
        Ok((canon, source))
    }

    fn mode_for(&self, inline_opt: bool) -> Mode {
        if self.profile == BundleProfile::SingleFile || inline_opt {
            Mode::Inline
        } else {
            Mode::Bundled
        }
    }

    fn insert(&mut self, key: String, a: Asset) -> Result<(), String> {
        if self.assets.insert(key.clone(), a).is_some() {
            return Err(format!("two assets would be keyed `{key}`"));
        }
        Ok(())
    }

    fn add_local(
        &mut self,
        key: String,
        widget: &str,
        rel: &str,
        inline_opt: bool,
    ) -> Result<(), String> {
        let (canon, source) = self.local(widget, rel)?;
        let (sha, bytes) = hash_file(&canon)?;
        let ext = safe_ext(rel);
        let a = Asset {
            mode: self.mode_for(inline_opt),
            mime: fold::mime_for(&ext).to_string(),
            sha,
            bytes,
            ext,
            source: Some(source),
            url: None,
            data: Bytes::File(canon),
        };
        self.insert(key, a)
    }

    fn add_mem(
        &mut self,
        key: String,
        ext: &str,
        data: Vec<u8>,
        inline_opt: bool,
    ) -> Result<(), String> {
        let a = Asset {
            mode: self.mode_for(inline_opt),
            mime: fold::mime_for(ext).to_string(),
            sha: sha_of(&data),
            bytes: data.len() as u64,
            ext: ext.to_string(),
            source: None,
            url: None,
            data: Bytes::Mem(data),
        };
        self.insert(key, a)
    }

    /// A remote asset: hashed from the local copy when there is one. With no
    /// local copy the hash needs a download, which is refused unless this
    /// export carries the user's approval for that url.
    fn add_remote(
        &mut self,
        key: String,
        widget: &str,
        role: &str,
        url: &str,
        local: Option<&str>,
        declared_sha: Option<&str>,
    ) -> Result<(), String> {
        if !url.starts_with("https://") || url.len() < 9 {
            return Err(format!(
                "widget {widget}: remote asset {role} must be an https url, not `{url}`"
            ));
        }
        let ext = safe_ext(url.split(['?', '#']).next().unwrap_or(url));
        let (sha, bytes, source) = match local {
            Some(rel) => {
                let (canon, source) = self.local(widget, rel)?;
                let (sha, bytes) = hash_file(&canon)?;
                (sha, bytes, Some(source))
            }
            None => {
                if !self.opts.approved_fetch.iter().any(|u| u == url) {
                    return Err(format!(
                        "widget {widget}: remote asset {role} ({url}) has no local copy, so hashing it needs a download. Maleficium does not fetch on its own: the user has to approve downloading that url for this export, and an agent cannot grant it. Put a local copy of the file next to the paper, or approve the download in the app."
                    ));
                }
                let Some(f) = self.opts.fetcher else {
                    return Err(format!(
                        "widget {widget}: remote asset {role} ({url}) was approved for download, but this build has no downloader"
                    ));
                };
                let data = f.fetch(url)?;
                (sha_of(&data), data.len() as u64, None)
            }
        };
        if let Some(d) = declared_sha {
            if !d.eq_ignore_ascii_case(&sha) {
                return Err(format!(
                    "widget {widget}: sha256 {d} does not match the {role} file (computed {sha})"
                ));
            }
        }
        let a = Asset {
            mode: Mode::Remote,
            mime: fold::mime_for(&ext).to_string(),
            sha,
            bytes,
            ext,
            source,
            url: Some(url.to_string()),
            data: Bytes::None,
        };
        self.insert(key, a)
    }
}

fn json_number_or_string(v: &str) -> Value {
    if !v.is_empty() && v.len() < 15 && v.bytes().all(|c| c.is_ascii_digit()) {
        v.parse::<u64>().map_or_else(|_| v.into(), Value::from)
    } else {
        v.into()
    }
}

/// The rendered region of a page, as a PNG: what a table's typeset rows look
/// like in the pdf of record.
fn crop_png(pdf: &hayro::hayro_syntax::Pdf, page: u32, r: &WidgetRect) -> Result<Vec<u8>, String> {
    use hayro::vello_cpu::color::palette::css::WHITE;
    use hayro::vello_cpu::Pixmap;
    std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let p = &pdf.pages()[page as usize - 1];
        let (_, page_h) = p.render_dimensions();
        let width_pt = ((r.x1 - r.x0) as f32).max(1.0);
        let scale = 2.0f32.min(1600.0 / width_pt);
        let settings = hayro::RenderSettings {
            x_scale: scale,
            y_scale: scale,
            bg_color: WHITE,
            ..Default::default()
        };
        let full = hayro::render(
            p,
            &hayro::RenderCache::new(),
            &hayro::hayro_interpret::InterpreterSettings::default(),
            &settings,
        );
        let (w, h) = (full.width() as usize, full.height() as usize);
        let px = |v: f32, hi: usize| ((v * scale).max(0.0) as usize).min(hi);
        let (x0, x1) = (
            px(r.x0 as f32, w),
            (((r.x1 as f32) * scale).ceil() as usize).min(w),
        );
        let (y0, y1) = (
            px(page_h - r.y1 as f32, h),
            (((page_h - r.y0 as f32) * scale).ceil() as usize).min(h),
        );
        if x1 <= x0 || y1 <= y0 {
            return Err(format!("the widget's rect lies outside page {page}"));
        }
        let mut buf = Vec::with_capacity((x1 - x0) * (y1 - y0));
        for row in y0..y1 {
            buf.extend_from_slice(&full.data()[row * w + x0..row * w + x1]);
        }
        Pixmap::from_parts(buf, (x1 - x0) as u16, (y1 - y0) as u16)
            .into_png()
            .map_err(|e| format!("cannot encode the table crop: {e}"))
    }))
    .map_err(|_| format!("the renderer failed on page {page}"))?
}

/// The generated host document of a built-in runtime this build ships.
pub(crate) fn runtime_host(runtime: &str) -> Option<&'static str> {
    match runtime {
        "table@1" => Some(TABLE_HOST),
        "chart@1" => Some(CHART_HOST),
        _ => None,
    }
}

/// A widget's local sources keyed by role; a repeated role gets `-2`,
/// `-3`, ... in document order.
pub(crate) fn role_keys(w: &Widget) -> Result<Vec<(String, &WidgetSource)>, String> {
    let mut seen: BTreeMap<&str, u32> = BTreeMap::new();
    let mut out = Vec::new();
    for s in &w.sources {
        if s.role.is_empty()
            || !s
                .role
                .bytes()
                .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit())
        {
            return Err(format!(
                "widget {}: source role `{}` is not a plain word",
                w.id, s.role
            ));
        }
        let n = seen.entry(&s.role).or_insert(0);
        *n += 1;
        let key = if *n == 1 {
            s.role.clone()
        } else {
            format!("{}-{}", s.role, n)
        };
        out.push((key, s));
    }
    Ok(out)
}

/// The options a runtime receives: everything but the export-only keys,
/// digits as numbers.
pub(crate) fn runtime_options(w: &Widget) -> Map<String, Value> {
    w.options
        .iter()
        .filter(|o| !matches!(o.key.as_str(), "remote" | "sha256" | "inline"))
        .map(|o| (o.key.clone(), json_number_or_string(&o.value)))
        .collect()
}

/// An `html` widget's bundle folder, resolved inside the project.
pub(crate) fn bundle_folder(
    cx: &Core,
    root_id: &str,
    main_dir_rel: &Path,
    w: &Widget,
) -> Result<PathBuf, String> {
    let rel = w
        .sources
        .iter()
        .find(|s| s.role == "bundle")
        .map(|s| s.path.trim_end_matches('/').to_string())
        .ok_or_else(|| format!("widget {}: an html widget records no bundle", w.id))?;
    let joined = main_dir_rel.join(&rel);
    crate::fs::resolve_in(cx, root_id, &joined.to_string_lossy())
        .map_err(|e| format!("widget {}: bundle folder {rel}: {e}", w.id))
}

/// A widget document that shows the poster: what a widget exports as when
/// its runtime is not in this build.
fn poster_document(alt: &str, poster: &Asset, policy: &str) -> Result<String, String> {
    let bytes = match &poster.data {
        Bytes::File(p) => std::fs::read(p).map_err(|e| format!("cannot read the poster: {e}"))?,
        Bytes::Mem(b) => b.clone(),
        Bytes::None => return Err("a poster cannot be remote".to_string()),
    };
    let url = format!(
        "data:{};base64,{}",
        poster.mime,
        base64::engine::general_purpose::STANDARD.encode(bytes)
    );
    Ok(fold::with_policy(
        &format!(
            "<!doctype html><html lang=\"en\"><head><title>{}</title><style>html,body{{margin:0;height:100%;background:var(--m-figure-bg,#fff)}}img{{display:block;width:100%;height:100%;object-fit:contain}}</style></head><body><img src=\"{url}\" alt=\"{}\"></body></html>",
            fold::text(alt),
            fold::attr(alt)
        ),
        policy,
    ))
}

fn plan_widget(
    p: &mut Plan,
    w: &Widget,
    pdf: &hayro::hayro_syntax::Pdf,
    pdf_pages: u32,
) -> Result<Planned, String> {
    let id = w.id.clone();
    if w.page < 1 || w.page > pdf_pages {
        return Err(format!(
            "widget {id}: page {} is outside the pdf's {pdf_pages} pages",
            w.page
        ));
    }
    let mb = pdf.pages()[w.page as usize - 1].media_box();
    let slack = 1.0;
    if w.rect.x0 >= w.rect.x1
        || w.rect.y0 >= w.rect.y1
        || w.rect.x0 < mb.x0 - slack
        || w.rect.y0 < mb.y0 - slack
        || w.rect.x1 > mb.x1 + slack
        || w.rect.y1 > mb.y1 + slack
    {
        return Err(format!(
            "widget {id}: its rect lies outside the media box of page {}",
            w.page
        ));
    }
    let inline_opt = option(w, "inline").is_some_and(truthy);
    let remote = option(w, "remote").filter(|r| !r.is_empty());
    if remote.is_some() && w.kind != WidgetType::Video {
        return Err(format!(
            "widget {id}: remote= is only supported on video widgets"
        ));
    }

    // The poster: the table's typeset rows are cropped from the pdf.
    let poster_key = format!("{id}-poster");
    if w.kind == WidgetType::Table {
        let png = crop_png(pdf, w.page, &w.rect).map_err(|e| format!("widget {id}: {e}"))?;
        p.add_mem(poster_key.clone(), "png", png, inline_opt)?;
    } else {
        let rel = w
            .poster
            .as_deref()
            .ok_or_else(|| format!("widget {id}: it records no poster"))?;
        p.add_local(poster_key.clone(), &id, rel, inline_opt)?;
    }

    let mut sources = Map::new();
    let policy = fold::widget_policy(w.csp.as_ref());

    let doc: String = if w.kind == WidgetType::Html {
        let dir = bundle_folder(p.cx, p.root_id, &p.main_dir_rel, w)?;
        let folded = fold::fold_bundle(&dir, &dir.join("index.html"), &policy)
            .map_err(|e| format!("widget {id}: {e}"))?;
        if !folded.unfolded.is_empty() {
            let shown: Vec<_> = folded.unfolded.iter().take(8).cloned().collect();
            let more = folded.unfolded.len() - shown.len();
            p.warn(
                BundleWarningKind::UnfoldedFiles,
                format!(
                    "widget {id}: files not inlined, so a page that fetches them at run time will not find them: {}{}",
                    shown.join(", "),
                    if more > 0 { format!(" and {more} more") } else { String::new() }
                ),
            );
        }
        for e in &folded.external {
            p.warn(
                BundleWarningKind::ExternalReference,
                format!("widget {id}: references {e}, which its policy blocks unless widget.json declares the origin"),
            );
        }
        for n in &folded.notes {
            p.warn(BundleWarningKind::FoldLimit, format!("widget {id}: {n}"));
        }
        folded.html
    } else {
        let mut video_local: Option<&str> = None;
        for (role_key, s) in role_keys(w)? {
            if w.kind == WidgetType::Video && s.role == "video" && remote.is_some() {
                video_local = Some(&s.path);
                continue;
            }
            let key = format!("{id}-{role_key}");
            p.add_local(key.clone(), &id, &s.path, inline_opt)?;
            sources.insert(role_key, key.into());
        }
        if let Some(url) = remote {
            let key = format!("{id}-video");
            p.add_remote(
                key.clone(),
                &id,
                "video",
                url,
                video_local,
                option(w, "sha256").filter(|s| !s.is_empty()),
            )?;
            sources.insert("video".into(), key.into());
        }
        let required = match w.kind {
            WidgetType::Model => Some("model"),
            WidgetType::Video => Some("video"),
            WidgetType::Table => Some("data"),
            WidgetType::Chart => Some("spec"),
            WidgetType::Html => None,
        };
        if let Some(role) = required {
            if !sources.contains_key(role) {
                return Err(format!("widget {id}: it records no {role} source"));
            }
        }
        let host = w.runtime.as_deref().and_then(runtime_host);
        match host {
            Some(html) => fold::with_policy(html, &policy),
            None => {
                p.warn(
                    BundleWarningKind::NoRuntime,
                    format!(
                        "widget {id}: no {} runtime in this build, so it exports as its poster",
                        w.runtime.as_deref().unwrap_or("built-in")
                    ),
                );
                let poster = &p.assets[&poster_key];
                poster_document(&w.alt, poster, &policy).map_err(|e| format!("widget {id}: {e}"))?
            }
        }
    };
    let entry =
        (p.profile != BundleProfile::SingleFile).then(|| format!("widgets/{id}/index.html"));

    let mut j = Map::new();
    j.insert("id".into(), id.clone().into());
    j.insert(
        "type".into(),
        serde_json::to_value(w.kind).map_err(|e| e.to_string())?,
    );
    if w.kind != WidgetType::Html {
        j.insert("runtime".into(), w.runtime.clone().into());
    }
    if let Some(e) = entry {
        j.insert("entry".into(), e.into());
    }
    j.insert("page".into(), w.page.into());
    j.insert(
        "rect".into(),
        json!([w.rect.x0, w.rect.y0, w.rect.x1, w.rect.y1]),
    );
    if let Some(l) = &w.label {
        j.insert("label".into(), l.clone().into());
    }
    if let Some(f) = &w.figure {
        j.insert("figure".into(), f.clone().into());
    }
    j.insert("poster".into(), poster_key.into());
    j.insert("alt".into(), w.alt.clone().into());
    if w.kind != WidgetType::Html {
        j.insert("sources".into(), Value::Object(sources));
    }
    let opts = runtime_options(w);
    if !opts.is_empty() {
        j.insert("options".into(), Value::Object(opts));
    }
    if let Some(c) = &w.csp {
        j.insert(
            "csp".into(),
            serde_json::to_value(c).map_err(|e| e.to_string())?,
        );
    }
    Ok(Planned {
        json: Value::Object(j),
        id,
        doc,
    })
}

// ---- the house theme ----------------------------------------------------

pub(crate) const THEME_CSS: &str = ".m-reader{--m-font-body:\"Libertinus Serif\",Georgia,serif;--m-font-heading:\"Libertinus Sans\",system-ui,sans-serif;--m-font-mono:\"Libertinus Mono\",ui-monospace,monospace;--m-font-math:\"Libertinus Math\",math;--m-size-base:1.0625rem;--m-scale:1.2;--m-size-small:0.875em;--m-leading:1.6;--m-measure:68ch;--m-figure-max:min(100%,64rem);--m-space-1:0.25rem;--m-space-2:0.5rem;--m-space-3:1rem;--m-space-4:1.5rem;--m-space-5:2.5rem;--m-space-6:4rem;--m-radius:6px;--m-color-bg:#fbfaf7;--m-color-surface:#f1efe9;--m-color-text:#1e1b24;--m-color-muted:#6b6676;--m-color-rule:#d9d5e0;--m-color-link:#5b2a86;--m-color-accent:#5b2a86;--m-color-target:#fff4c2;--m-figure-bg:#ffffff}\n.m-reader[data-theme=\"dark\"]{--m-color-bg:#16181d;--m-color-surface:#1f2229;--m-color-text:#dfe1e6;--m-color-muted:#9aa1ad;--m-color-rule:#343944;--m-color-link:#b79ad4;--m-color-accent:#b79ad4;--m-color-target:#3a3420}\n";

fn theme_json(id: &str) -> String {
    let v = json!({
        "id": id,
        "name": "Maleficium house",
        "contractVersion": CONTRACT_VERSION,
        "author": "Maleficium contributors",
        "license": "Apache-2.0",
        "modes": ["light", "dark"],
        "css": ["theme.css"],
        "fonts": []
    });
    serde_json::to_string_pretty(&v).unwrap_or_default() + "\n"
}

// ---- manifest -----------------------------------------------------------

fn validator() -> Result<jsonschema::Validator, String> {
    let schema: Value = serde_json::from_str(MANIFEST_SCHEMA)
        .map_err(|e| format!("the committed manifest schema is not json: {e}"))?;
    jsonschema::validator_for(&schema).map_err(|e| format!("the manifest schema is invalid: {e}"))
}

/// Checks a manifest against the committed schema and the invariants the
/// schema cannot express. Every violation is named.
pub fn validate_manifest(m: &Value) -> Result<(), String> {
    let v = validator()?;
    let errors: Vec<String> = v
        .iter_errors(m)
        .map(|e| format!("{} at {}", e, e.instance_path()))
        .collect();
    if !errors.is_empty() {
        return Err(format!(
            "the manifest breaks its schema: {}",
            errors.join("; ")
        ));
    }
    let widgets = m["widgets"].as_array().cloned().unwrap_or_default();
    let assets = m["assets"].as_object().cloned().unwrap_or_default();
    let pages = m["pdf"]["pages"].as_u64().unwrap_or(0);
    let profile = m.get("profile").and_then(Value::as_str).unwrap_or("folder");
    let mut ids = BTreeSet::new();
    let mut last: Option<(u64, f64)> = None;
    for w in &widgets {
        let id = w["id"].as_str().unwrap_or("");
        if !ids.insert(id.to_string()) {
            return Err(format!("widget id `{id}` appears twice"));
        }
        let refs = std::iter::once(w["poster"].as_str()).chain(
            w.get("sources")
                .and_then(Value::as_object)
                .into_iter()
                .flat_map(|s| s.values().map(Value::as_str)),
        );
        for r in refs {
            let r = r.unwrap_or("");
            if !assets.contains_key(r) {
                return Err(format!(
                    "widget {id} names asset `{r}`, which does not exist"
                ));
            }
        }
        let page = w["page"].as_u64().unwrap_or(0);
        if page > pages {
            return Err(format!("widget {id} is on page {page} of {pages}"));
        }
        let r: Vec<f64> = w["rect"]
            .as_array()
            .map(|a| a.iter().filter_map(Value::as_f64).collect())
            .unwrap_or_default();
        if r.len() != 4 || r[0] >= r[2] || r[1] >= r[3] {
            return Err(format!("widget {id} has a rect that is not x0<x1, y0<y1"));
        }
        // Document order: page, then top to bottom.
        let top = r[3];
        if let Some((lp, lt)) = last {
            if page < lp || (page == lp && top > lt) {
                return Err(format!("widget {id} is out of document order"));
            }
        }
        last = Some((page, top));
        if profile == "single-file" && w.get("entry").is_some() {
            return Err(format!("widget {id} has an entry in a single-file bundle"));
        }
    }
    if profile == "single-file" {
        if assets.values().any(|a| a["mode"] == "bundled") {
            return Err("a single-file bundle has a bundled asset".to_string());
        }
        if !m["pdf"]["path"].is_null() {
            return Err("a single-file bundle must inline its pdf".to_string());
        }
    } else if m["pdf"]["path"] != "paper.pdf" {
        return Err("a folder or hosted bundle keeps its pdf at paper.pdf".to_string());
    }
    Ok(())
}

// ---- writing ------------------------------------------------------------

/// Serializes JSON for a `<script type="application/json">` island: `<` is
/// escaped so no string can close the element.
fn island(id: &str, v: &Value) -> String {
    let s = serde_json::to_string(v)
        .unwrap_or_default()
        .replace('<', "\\u003c");
    format!("<script type=\"application/json\" id=\"{id}\">{s}</script>")
}

fn placeholder_reader(title: &str, authors: &[String], folder: bool, islands: &str) -> String {
    let policy = if folder {
        fold::FOLDER_READER_POLICY
    } else {
        fold::SINGLE_FILE_READER_POLICY
    };
    let pdf = if folder {
        "<p><a href=\"paper.pdf\">paper.pdf</a> is the version of record.</p>"
    } else {
        "<p>The version of record is embedded in this file.</p>"
    };
    let by = authors
        .iter()
        .filter(|a| !a.is_empty())
        .map(|a| fold::text(a))
        .collect::<Vec<_>>()
        .join(", ");
    let head = fold::with_policy(
        &format!(
            "<!doctype html><html lang=\"en\"><head><title>{0}</title></head><body><main><h1>{0}</h1><p>{by}</p><p>This bundle's reader is not part of this build. The manifest, the paper and every widget are complete.</p>{pdf}</main>",
            fold::text(title)
        ),
        policy,
    );
    format!("{head}{islands}</body></html>\n")
}

fn read_verified(path: &Path, sha: &str) -> Result<Vec<u8>, String> {
    let b = std::fs::read(path).map_err(|e| format!("cannot read {}: {e}", path.display()))?;
    if sha_of(&b) != sha {
        return Err(format!(
            "{} changed while it was being exported: run the export again",
            path.display()
        ));
    }
    Ok(b)
}

fn put(root: &Path, rel: &str, bytes: &[u8], total: &mut u64) -> Result<(), String> {
    let p = root.join(rel);
    if let Some(parent) = p.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|e| format!("cannot create {}: {e}", parent.display()))?;
    }
    std::fs::File::create(&p)
        .and_then(|mut f| f.write_all(bytes))
        .map_err(|e| format!("cannot write {}: {e}", p.display()))?;
    *total += bytes.len() as u64;
    Ok(())
}

/// Whether `dir` holds an earlier bundle of ours (its manifest names the
/// format): the only non-empty folder an export replaces.
fn is_earlier_bundle(dir: &Path) -> bool {
    std::fs::read_to_string(dir.join("manifest.json"))
        .ok()
        .and_then(|t| serde_json::from_str::<Value>(&t).ok())
        .is_some_and(|v| v["format"] == FORMAT)
}

/// What an export may do at `dest` before anything is written.
fn check_destination(root: &Path, dest: &str, profile: BundleProfile) -> Result<PathBuf, String> {
    let out = crate::export::destination(root, dest)?;
    if root.starts_with(&out) {
        return Err(
            "export destination contains the project: choose a folder outside it".to_string(),
        );
    }
    match std::fs::symlink_metadata(&out) {
        Err(_) => {}
        Ok(m) if m.file_type().is_symlink() => {
            return Err(format!(
                "export destination is a symlink: {}",
                out.display()
            ));
        }
        Ok(m) => match profile {
            BundleProfile::SingleFile => {
                if m.is_dir() {
                    return Err(format!("export destination is a folder: {}", out.display()));
                }
            }
            _ => {
                if !m.is_dir() {
                    return Err(format!("export destination is a file: {}", out.display()));
                }
                let empty = std::fs::read_dir(&out)
                    .map_err(|e| format!("cannot list {}: {e}", out.display()))?
                    .next()
                    .is_none();
                if !empty && !is_earlier_bundle(&out) {
                    return Err(format!(
                        "export destination is not empty and is not an earlier bundle: {}",
                        out.display()
                    ));
                }
            }
        },
    }
    Ok(out)
}

fn staging_name(out: &Path) -> PathBuf {
    let name = out
        .file_name()
        .map(|n| n.to_string_lossy().to_string())
        .unwrap_or_default();
    out.with_file_name(format!(".{name}.mfw-partial-{}", std::process::id()))
}

/// Exports a paper bundle with no network and no approvals: the call the
/// automation surface makes.
pub fn export_bundle(
    cx: &Core,
    root_id: &str,
    main_rel: &str,
    dest: &str,
    profile: BundleProfile,
    size_cap_bytes: Option<u64>,
) -> Result<BundleExported, String> {
    export_bundle_with(
        cx,
        root_id,
        main_rel,
        dest,
        profile,
        &BundleOptions {
            size_cap_bytes,
            ..BundleOptions::default()
        },
    )
}

/// Exports a paper bundle of `main_rel`'s last compile to `dest`, outside the
/// project.
pub fn export_bundle_with(
    cx: &Core,
    root_id: &str,
    main_rel: &str,
    dest: &str,
    profile: BundleProfile,
    opts: &BundleOptions,
) -> Result<BundleExported, String> {
    let root = crate::fs::session_root(cx, root_id)?;
    let out = check_destination(&root, dest, profile)?;

    // The typed widget list is the join of sidecar and pdf; it also fails when
    // the main file was never compiled.
    let list = crate::widgets::widgets(cx, root_id, main_rel)?;
    let o = crate::outputs::outputs_of(cx, root_id, main_rel)?;
    let pdf_bytes = std::fs::read(o.outdir.join(&o.pdf_name))
        .map_err(|_| format!("{main_rel} has no compiled pdf: compile it first"))?;
    let pdf = hayro::hayro_syntax::Pdf::new(pdf_bytes.clone())
        .map_err(|e| format!("cannot read the pdf of {main_rel}: {e:?}"))?;
    let pages = pdf.pages().len() as u32;
    if pages == 0 || pdf_bytes.is_empty() {
        return Err(format!("the pdf of {main_rel} has no pages"));
    }

    let mut theme_ids: BTreeSet<&str> = list.widgets.iter().map(|w| w.theme.as_str()).collect();
    if theme_ids.is_empty() {
        theme_ids.insert("house");
    }
    if theme_ids.len() > 1 {
        return Err(format!(
            "the widgets name more than one theme ({}): the paper has one",
            theme_ids.iter().copied().collect::<Vec<_>>().join(", ")
        ));
    }
    let theme_id = theme_ids.into_iter().next().unwrap_or("house").to_string();
    if theme_id != "house" {
        return Err(format!(
            "theme `{theme_id}` is not available: only the built-in house theme is in this build"
        ));
    }

    let mut plan = Plan {
        cx,
        root_id,
        root: root.clone(),
        main_dir_rel: Path::new(main_rel)
            .parent()
            .map(Path::to_path_buf)
            .unwrap_or_default(),
        profile,
        opts,
        assets: BTreeMap::new(),
        warnings: Vec::new(),
    };

    let stem = o
        .main_file
        .strip_suffix(".tex")
        .unwrap_or(&o.main_file)
        .to_string();
    let tex = std::fs::read_to_string(root.join(&plan.main_dir_rel).join(&o.main_file))
        .map_err(|e| format!("cannot read {main_rel}: {e}"))?;
    let meta = paper_meta(&tex, &stem, &mut plan.warnings);

    let mut planned = Vec::new();
    for w in &list.widgets {
        planned.push(plan_widget(&mut plan, w, &pdf, pages)?);
    }

    let mut paper = Map::new();
    paper.insert("title".into(), meta.title.clone().into());
    paper.insert(
        "authors".into(),
        Value::Array(
            meta.authors
                .iter()
                .map(|(n, aff)| {
                    let mut a = Map::new();
                    a.insert("name".into(), n.clone().into());
                    if !aff.is_empty() {
                        a.insert("affiliations".into(), json!(aff));
                    }
                    Value::Object(a)
                })
                .collect(),
        ),
    );
    if let Some(a) = &meta.abstract_text {
        paper.insert("abstract".into(), a.clone().into());
    }
    let single = profile == BundleProfile::SingleFile;
    let cap = opts.size_cap_bytes.unwrap_or(DEFAULT_SIZE_CAP_BYTES);
    let mut manifest = Map::new();
    manifest.insert("format".into(), FORMAT.into());
    manifest.insert("formatVersion".into(), 1.into());
    manifest.insert(
        "generator".into(),
        json!({ "name": "maleficium", "version": env!("CARGO_PKG_VERSION") }),
    );
    manifest.insert(
        "profile".into(),
        serde_json::to_value(profile).map_err(|e| e.to_string())?,
    );
    if single {
        manifest.insert("sizeCapBytes".into(), cap.into());
    }
    manifest.insert("paper".into(), Value::Object(paper));
    manifest.insert(
        "pdf".into(),
        json!({
            "path": if single { Value::Null } else { "paper.pdf".into() },
            "sha256": sha_of(&pdf_bytes),
            "bytes": pdf_bytes.len(),
            "pages": pages
        }),
    );
    manifest.insert(
        "theme".into(),
        json!({ "id": theme_id, "contractVersion": CONTRACT_VERSION }),
    );
    manifest.insert(
        "widgets".into(),
        Value::Array(planned.iter().map(|p| p.json.clone()).collect()),
    );
    manifest.insert(
        "assets".into(),
        Value::Object(
            plan.assets
                .iter()
                .map(|(k, a)| (k.clone(), a.record()))
                .collect(),
        ),
    );
    let manifest = Value::Object(manifest);
    validate_manifest(&manifest)?;

    // Writing starts only now: every read, hash and check above has passed.
    let stage = staging_name(&out);
    let _ = std::fs::remove_dir_all(&stage);
    let _ = std::fs::remove_file(&stage);
    let mut total = 0u64;
    let manifest_text = serde_json::to_string_pretty(&manifest).map_err(|e| e.to_string())? + "\n";
    let authors: Vec<String> = meta.authors.iter().map(|a| a.0.clone()).collect();

    let written = (|| -> Result<(), String> {
        if single {
            let mut assets = Map::new();
            for a in plan.assets.values().filter(|a| a.mode == Mode::Inline) {
                if assets.contains_key(&a.sha) {
                    continue;
                }
                let bytes = match &a.data {
                    Bytes::File(p) => read_verified(p, &a.sha)?,
                    Bytes::Mem(b) => b.clone(),
                    Bytes::None => continue,
                };
                assets.insert(
                    a.sha.clone(),
                    base64::engine::general_purpose::STANDARD
                        .encode(bytes)
                        .into(),
                );
            }
            let widgets: Map<String, Value> = planned
                .iter()
                .map(|p| (p.id.clone(), p.doc.clone().into()))
                .collect();
            let islands = [
                island("mfw-manifest", &manifest),
                island("mfw-widgets", &Value::Object(widgets)),
                island("mfw-assets", &Value::Object(assets)),
                island(
                    "mfw-pdf",
                    &base64::engine::general_purpose::STANDARD
                        .encode(&pdf_bytes)
                        .into(),
                ),
            ]
            .concat();
            let html = placeholder_reader(&meta.title, &authors, false, &islands);
            std::fs::write(&stage, html.as_bytes())
                .map_err(|e| format!("cannot write {}: {e}", stage.display()))?;
            total = html.len() as u64;
        } else {
            std::fs::create_dir_all(&stage)
                .map_err(|e| format!("cannot create {}: {e}", stage.display()))?;
            put(
                &stage,
                "manifest.json",
                manifest_text.as_bytes(),
                &mut total,
            )?;
            put(&stage, "paper.pdf", &pdf_bytes, &mut total)?;
            put(
                &stage,
                "theme/theme.json",
                theme_json(&theme_id).as_bytes(),
                &mut total,
            )?;
            put(&stage, "theme/theme.css", THEME_CSS.as_bytes(), &mut total)?;
            for p in &planned {
                put(
                    &stage,
                    &format!("widgets/{}/index.html", p.id),
                    p.doc.as_bytes(),
                    &mut total,
                )?;
            }
            let mut inline = Map::new();
            let mut stored = BTreeSet::new();
            for a in plan.assets.values() {
                let bytes = match (&a.data, a.mode) {
                    (_, Mode::Remote) | (Bytes::None, _) => continue,
                    (Bytes::File(p), _) => read_verified(p, &a.sha)?,
                    (Bytes::Mem(b), _) => b.clone(),
                };
                if a.mode == Mode::Inline {
                    inline.insert(
                        a.sha.clone(),
                        base64::engine::general_purpose::STANDARD
                            .encode(&bytes)
                            .into(),
                    );
                } else if stored.insert(a.path()) {
                    put(&stage, &a.path(), &bytes, &mut total)?;
                }
            }
            let islands = [
                island("mfw-manifest", &manifest),
                if inline.is_empty() {
                    String::new()
                } else {
                    island("mfw-assets", &Value::Object(inline))
                },
            ]
            .concat();
            let html = placeholder_reader(&meta.title, &authors, true, &islands);
            put(&stage, "index.html", html.as_bytes(), &mut total)?;
        }
        Ok(())
    })();
    if let Err(e) = written {
        let _ = std::fs::remove_dir_all(&stage);
        let _ = std::fs::remove_file(&stage);
        return Err(e);
    }

    if single && total > cap {
        plan.warn(
            BundleWarningKind::SizeCap,
            format!(
                "the single-file bundle is {total} bytes, over the {cap} byte cap; it was written anyway"
            ),
        );
    }

    let moved = (|| -> Result<(), String> {
        match std::fs::symlink_metadata(&out) {
            Ok(m) if m.is_dir() => {
                std::fs::remove_dir_all(&out)
                    .map_err(|e| format!("cannot replace {}: {e}", out.display()))?;
            }
            Ok(_) => {
                std::fs::remove_file(&out)
                    .map_err(|e| format!("cannot replace {}: {e}", out.display()))?;
            }
            Err(_) => {}
        }
        std::fs::rename(&stage, &out)
            .map_err(|e| format!("cannot place the bundle at {}: {e}", out.display()))
    })();
    if let Err(e) = moved {
        let _ = std::fs::remove_dir_all(&stage);
        let _ = std::fs::remove_file(&stage);
        return Err(e);
    }

    Ok(BundleExported {
        path: out.to_string_lossy().to_string(),
        profile,
        bytes: total,
        widgets: planned.len() as u32,
        assets: plan.assets.len() as u32,
        warnings: plan.warnings,
    })
}

/// The bus event for one export call, shared by the adapters that log it.
pub fn event(
    main_rel: &str,
    profile: BundleProfile,
    r: &Result<BundleExported, String>,
    actor: maleficium_events::Actor,
) -> maleficium_events::BusEvent {
    use maleficium_events::{AppEvent, BusEvent, EventKind, EventScope};
    let (kind, message, event) = match r {
        Ok(b) => (
            if b.warnings.is_empty() {
                EventKind::Success
            } else {
                EventKind::Warn
            },
            format!(
                "exported a {} bundle of {main_rel} to {}",
                profile_name(profile),
                b.path
            ),
            AppEvent::BundleExported {
                main: main_rel.to_string(),
                profile,
                path: b.path.clone(),
                bytes: b.bytes,
                widgets: b.widgets,
                warnings: b.warnings.len() as u32,
            },
        ),
        Err(e) => (
            EventKind::Error,
            format!("bundle export of {main_rel} refused"),
            AppEvent::BundleFailed {
                main: main_rel.to_string(),
                profile,
                error: e.chars().take(300).collect(),
            },
        ),
    };
    BusEvent {
        at: crate::eventlog::now_ms(),
        scope: EventScope::App,
        kind,
        actor,
        message,
        event,
    }
}

fn profile_name(p: BundleProfile) -> &'static str {
    match p {
        BundleProfile::Folder => "folder",
        BundleProfile::SingleFile => "single-file",
        BundleProfile::Hosted => "hosted",
    }
}

#[cfg(test)]
mod tests;
